section4 データベース
traPtitech/naro-text pull request #11
Opened 2023-05-24 01:57 UTC by ikura-hamu

2023-05-27 12:30 UTC, hijiki51 requested changes

2023-05-27 12:30 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +:::danger 注意
infoでいいです

2023-05-27 12:30 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +[Ubuntuにおけるapt , apt-get , aptitude の違いとは?](http://zaka-think.com/linux/ubuntu/ubuntu-apt-apt-get-aptitude/)
これページ消えてるから削除してください

2023-05-27 12:30 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +:::warning 注意
tips

2023-05-27 12:30 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +:::details `task`って何だ。
detailsで隠す必要はないかも

2023-05-27 12:30 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +task 公式ドキュメント https://taskfile.dev/
githubのリンクもあるとよいです

2023-05-28 15:04 UTC, Takeno-hito requested changes

2023-05-28 15:04 UTC, Takeno-hito commented on docs/chapter1/section4/2_sql.md
> +SELECT country.Name, city.Name FROM country LEFT JOIN city ON country.Code = city.CountryCode;
さらっと LEFT JOIN 使ってるけどヒント入れた方がいいかも？

2023-05-28 15:04 UTC, Takeno-hito commented on docs/chapter1/section4/2_sql.md
> +| RANK() OVER (ORDER BY Population DESC) | Name               | Population |
すごくどうでもいいけど as 使って `Rank` にしたくない？

2023-05-28 15:04 UTC, Takeno-hito commented on docs/chapter1/section4/2_sql.md
> +  RANK() OVER (ORDER BY SUM(countrylanguage.Percentage * country.Population / 100) DESC) AS "Rank",
手元で実行してないからできなかったら申し訳ないけど、 ORDER BY  `Speakers` とかいけないですか？

2023-05-28 22:14 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +`mysql -u root`は、「MySQL を`root`というユーザーで使うためにパスワードを使ってログインする」という意味のコマンドです。パスワードをつなげて`mysql -u root -ppassword`ともできます。
これなくても実は行ける

2023-05-28 22:15 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +`mysql -u root`は、「MySQL を`root`というユーザーで使うためにパスワードを使ってログインする」という意味のコマンドです。パスワードをつなげて`mysql -u root -ppassword`ともできます。
あると動かなかった気もするけどどうだっけ（未確認）

2023-05-28 22:17 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
これつけるとほんとに<>付けちゃう人続出するのでない方がいい

2023-05-28 22:42 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +今回は`task up`を実行したときに Adminer が立ち上がるようになっています。 http://localhost:8080 にアクセスすると使えます。
リンクにしちゃっていいと思う

2023-05-28 22:44 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`city`テーブルには`ID`、`Name`、`CountryCode`、`District`、`Population`の 5 つのカラムの存在がわかります。
インデックスは長くなるから別の章でいいと思う

2023-05-28 23:15 UTC, mehm8128 commented on docs/chapter1/section4/1_prepare.md
> +`mysql -u root`は、「MySQL を`root`というユーザーで使うためにパスワードを使ってログインする」という意味のコマンドです。パスワードをつなげて`mysql -u root -ppassword`ともできます。
あるとさらにパスワード入力させられた気がします&僕はいつも-uも-urootみたいにするので統一してもよさそう

2023-05-28 23:16 UTC, mehm8128 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
これ今後もよくやる書き方なので(フロントの章でも使ってますし)、さすがにどこかにちゃんと強調して書いておいて使っちゃっていいと思います

2023-05-28 23:23 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
確かに、じゃあせめてカッコの種類は統一した方がいいかも

[]か{}

2023-05-28 23:46 UTC, mehm8128 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
[]はあんまり見ない気するので{}ですかね🤔

2023-05-28 23:57 UTC, ikura-hamu commented on docs/chapter1/section4/1_prepare.md
> +`mysql -u root`は、「MySQL を`root`というユーザーで使うためにパスワードを使ってログインする」という意味のコマンドです。パスワードをつなげて`mysql -u root -ppassword`ともできます。
-uも繋げられるのは知らなかった。
こういうコマンドのオプションって大体スペース入る気がするので、入れた方がいい気もします。

2023-05-28 23:59 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +`city`テーブルには`ID`、`Name`、`CountryCode`、`District`、`Population`の 5 つのカラムの存在がわかります。
Goとdb繋げる話をした後に発展編みたいな感じでEXPLAINとかといっしょに扱えばいいですか。

2023-05-29 00:02 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +SELECT country.Name, city.Name FROM country LEFT JOIN city ON country.Code = city.CountryCode;
JOINの説明で複数種類あることは言ってるし、どちらにせよ応用編は調べないと解けないのでこれでいいと思ってた

2023-05-29 00:02 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +  RANK() OVER (ORDER BY SUM(countrylanguage.Percentage * country.Population / 100) DESC) AS "Rank",
これはできない

2023-05-29 00:22 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`city`テーブルには`ID`、`Name`、`CountryCode`、`District`、`Population`の 5 つのカラムの存在がわかります。
座学編にもろうかなぁ

ちょっと考えさせて

2023-05-29 02:06 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +さっき追加した大岡山の情報を変えてみましょう。
条件に当てはまる**すべての**レコードの値

とかでいいとおもう

2023-05-29 02:07 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT カラム名 FROM テーブル名 ORDERED BY 対象カラム名 並び順;`で結果を昇順・降順に並び替えて取得できます。`ASC`で昇順、`DESC`で降順です。
あとORDEREDになってる

2023-05-29 02:20 UTC, Takeno-hito commented on docs/chapter1/section4/1_prepare.md
> +`mysql -u root`は、「MySQL を`root`というユーザーで使うためにパスワードを使ってログインする」という意味のコマンドです。パスワードをつなげて`mysql -u root -ppassword`ともできます。
ごめんなさい、僕のミスで `-ppassword` じゃないと動かなかったです。 `-u` に関してはスペースが入ってもなくても動きました

2023-05-29 02:23 UTC, Takeno-hito commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
[] の方が見る気がします？ただどれが標準的かは僕はちょっと分からないのでおまかせします

2023-05-29 02:29 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
個人的に
- commandのドキュメントでのoptionalな引数定義とかは[]
- 変数代入は{}が多いと思う

2023-05-29 02:29 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
というか大体のテンプレートエンジンで `{{ var }}`が使われてるからそのイメージが強いかも(goしかり、jinjaしかり)

2023-05-29 02:30 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
プログラムに寄せるなら`${}`や`$var`が近いけど絶対伝わらん

2023-05-29 02:39 UTC, Takeno-hito commented on docs/chapter1/section4/2_sql.md
> +SELECT country.Name, city.Name FROM country LEFT JOIN city ON country.Code = city.CountryCode;
調べないと解けないのは確かにそうかも。それなら「`city`テーブルに都市が 1 つもない国もありますが、そのような国も出力してください。」を強調表示したい気持ちがあります（か、問題文中に取得レコード数が `4086` と書いておいてほしいです。解けたと思って回答みずに飛ばされちゃうかもだし）

2023-05-29 02:41 UTC, Takeno-hito commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
僕もその感覚です。だと `[]` の方が今回は適切ですかね？

2023-05-29 02:51 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
はい、ですが今回の講習会の用途だと変数代入が圧倒的に多いうえ、その二つを使い分けるのは受講者への認知コストが高いため{}でいいと思っています

2023-05-29 02:51 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT 対象カラム名 FROM 対象テーブル名;` で、テーブルから情報を取得できます。複数のカラムを取得したいときは`,`で区切ります。
周知させたいのは"かっこは取り除いて代入してください"ということなので

2023-05-29 04:15 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +:::details **答え**
これは太字にしないとlinterが「文末が。じゃない」と警告を出すので。設定で変えられるのかもしれないけど、調べる時間もったいないのでやってない。

2023-05-29 04:22 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +mysql> SELECT Name, District "Prefecture" FROM city WHERE CountryCode = "JPN";
上のやつと同じだけどいるかな

2023-05-29 04:44 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +:::details **答え**
そこは動くように設定調整してください

2023-05-29 04:44 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +:::details **答え**
textlintrc.jsonのallowlistに正規表現で入れられます

2023-05-29 04:45 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +:::details **答え**
https://github.com/textlint/textlint-filter-rule-allowlist

2023-05-29 04:46 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +:::details **答え**
そういう表記ブレを避けるためにtextlint入れたので

2023-05-29 06:44 UTC, Takeno-hito commented on docs/chapter1/section4/2_sql.md
> +mysql> SELECT Name, District "Prefecture" FROM city WHERE CountryCode = "JPN";
あー、2つ上と同じなのか 。だったら「`AS`はカラム名だけでなくテーブル名にも使うことができ、先ほどの`JOIN`の SQL は`AS`を使うとこのように書けます。」とこの話を入れ替えたい気持ちも少しあるかも？直さなくても問題ないかもだけど今のままだと同じかどうか若干分かりづらい気もします

2023-05-30 02:45 UTC, mehm8128 commented on docs/chapter1/section4/2_sql.md
> +さっき追加した大岡山の情報を変えてみましょう。
これ削除の方にも入れた方がよさそうです

2023-05-30 03:09 UTC, Takeno-hito commented on docs/chapter1/section4/1_prepare.md
> +:::info 注意
```suggestion
:::info
```

か、warning に変えるか info のコンテナで注意って書かれるのちょっと嬉しくない

2023-05-30 03:44 UTC, ras0q commented on docs/chapter1/section4/1_prepare.md
> +OS 標準のパッケージ管理ツールは Linux の種類ごとに違い、今回サーバーとして利用している Ubuntu では `apt` が使われています。
サーバーとして利用しているUbuntu、みたいな言い方あまり聞いたことないんですが一般的なんですかね？
うまい代替案をあげられないのですが、、(ディストリビューション？)
@hijiki51

2023-05-30 03:57 UTC, ikura-hamu commented on docs/chapter1/section4/1_prepare.md
> +OS 標準のパッケージ管理ツールは Linux の種類ごとに違い、今回サーバーとして利用している Ubuntu では `apt` が使われています。
これ去年までのを流用したんですけど、そもそも今回はサーバー立てないで手元でやるので間違ってました。
どちらにせよ正しい言い方は知りたいです。

2023-05-30 04:20 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +OS 標準のパッケージ管理ツールは Linux の種類ごとに違い、今回サーバーとして利用している Ubuntu では `apt` が使われています。
OS 標準のパッケージ管理ツールは OS の種類ごとに違います。
例えば、WSLでデフォルトでインストールされるUbuntuでは`apk`が用いられています

とか？

2023-05-30 05:10 UTC, ras0q commented on docs/chapter1/section4/1_prepare.md
> +OS 標準のパッケージ管理ツールは Linux の種類ごとに違い、今回サーバーとして利用している Ubuntu では `apt` が使われています。
前の文との繋がり考えると

パッケージ管理ツールはOSごとに様々なものがありますが、例えばWSLでデフォルトでインストールされるUbuntuというLinux OSでは`apt`というツールが標準で用意されています。

とか

2023-05-30 05:24 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +OS 標準のパッケージ管理ツールは Linux の種類ごとに違い、今回サーバーとして利用している Ubuntu では `apt` が使われています。
補足：厳密にはOSではないが、簡単のため、ここではOSと呼んでいる

2023-05-30 05:25 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +OS 標準のパッケージ管理ツールは Linux の種類ごとに違い、今回サーバーとして利用している Ubuntu では `apt` が使われています。
文章はよさそう

2023-05-30 05:34 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`city`テーブルには`ID`、`Name`、`CountryCode`、`District`、`Population`の 5 つのカラムの存在がわかります。
座学編資料に盛ることにした

さすがにスライドで説明すると時間無限に使うので

2023-05-30 05:35 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`city`テーブルには`ID`、`Name`、`CountryCode`、`District`、`Population`の 5 つのカラムの存在がわかります。
そうするとB-treeとかもかけるな()

2023-05-30 05:39 UTC, hijiki51 requested changes

2023-05-30 05:39 UTC, hijiki51 commented on .textlintrc.json
> +        "答え"
これだとほかのところも引っかかっちゃうので、
`/:::.*$/`みたいな正規表現でちゃんと対象絞ってください

2023-05-31 16:32 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
```suggestion
`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。ただし、`LIMIT`を指定せずに`OFFSET`を指定することはできません。
```

2023-05-31 16:33 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +SELECT 文の後ろに`LIMIT {件数}`を追加することで取得件数の上限を指定できます。
```suggestion
`SELECT` 文の後ろに`LIMIT {件数}`を追加することで取得件数の上限を指定できます。
```

2023-05-31 16:33 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`SELECT {カラム名} FROM {テーブル名} WHERE {条件式};`で取得するレコードの条件を付けることができます。`AND`や`OR`を使うと条件を複数つけることができます。
```suggestion
`SELECT {カラム名} FROM {テーブル名} WHERE {条件式};`で取得するレコードの条件を付けることができます。`AND`や`OR`を使うことで、条件を複数つけることができます。

2023-05-31 16:37 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +mysql> DESC countrylanguage;
`ASC` `DESC`と混ざるから、`DESCRIVE`か`SHOW`のほうがいいと思う

2023-05-31 16:39 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +## 演習問題
だいぶ長くなっちゃってるから「SQL演習」として別ページに切っていいかも

2023-06-02 08:22 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
「～～することは」みたいなやつが全部linterに怒られるんですけど、これも例外に含めた方がいいですか

2023-06-02 08:24 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
え、具体的になんて怒られてる？（僕の日本語がまずいのか）

2023-06-02 08:25 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
冗長だからこれだったら「指定できません」にしろって言われます

2023-06-02 08:25 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
生のエラー文が欲しいです

2023-06-02 08:26 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
冗長なのか・・・言われればdo specifyみたいな感じか

2023-06-02 08:26 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
<img width="713" alt="image" src="https://github.com/traPtitech/naro-text/assets/104292023/61c1ec2e-9821-4d9d-9e0e-838833193c5a">
こんな感じです

2023-06-02 08:28 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
エラー文をくださいといったときはスクショじゃなくてエラー文をコピペしてほしいです

2023-06-02 08:29 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
すみません
`【dict2】 "することはできませ"は冗長な表現です。"することは"を省き簡潔な表現にすると文章が明瞭になります。
解説: https://github.com/textlint-ja/textlint-rule-ja-no-redundant-expression#dict2 (ja-technical-writing/ja-no-redundant-expression)textlint(ja-technical-writing/ja-no-redundant-expression)`

2023-06-02 08:31 UTC, motoki317 commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
もしかして
```suggestion
`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`は指定できません。
```

2023-06-02 08:32 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
確かに

あとこれ例外も存在するらしい
https://qiita.com/takahi-i/items/a93dc2ff42af6b93f6e0#comment-850ec4d194748453a39a

2023-06-02 08:32 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
今回は例外じゃないけど

2023-06-02 08:34 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
tokiさんのやつみたいな感じで書きかえればいいですかね

2023-06-02 08:38 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +`OFFSET {ずらす数}`を LIMIT 句の後ろにつなげると、データを取得し始める位置をずらして指定できます。`LIMIT`を指定せずに`OFFSET`を指定できません。
全部が怒られてるわけではなさそうですね

2023-06-03 11:45 UTC, ikura-hamu commented
@mehm8128 localhostがdeadlink判定になるのってどうやって直しましたか？`![]()`にしてみるとか`linkify:false`とかやったのですが、わかりません。

2023-06-03 11:53 UTC, hijiki51 commented
<a href='http://localhost:5173/' target="_blank" rel="noopener noreferrer">localhost:5173</a>

2023-06-03 11:53 UTC, hijiki51 commented
```
<a href='http://localhost:5173/' target="_blank" rel="noopener noreferrer">localhost:5173</a>
```

こうしてるね

2023-06-03 11:53 UTC, hijiki51 commented
https://github.com/traPtitech/naro-text/pull/8/files#diff-1b11ac99341593e08fe22c329cf782f74cb40d5b88696341fa95e726449e47aeR69

2023-06-03 11:53 UTC, mehm8128 commented
https://github.com/traPtitech/naro-text/pull/8/files#diff-1b11ac99341593e08fe22c329cf782f74cb40d5b88696341fa95e726449e47aeR69
こんな感じにしたら上手くいった
なんでこれで上手くいくのかは知らないけどここに書いてあったからやってみた感じ
https://github.com/vuejs/vitepress/issues/822#issuecomment-1160655885

2023-06-03 11:54 UTC, mehm8128 commented
先に言われちゃった

2023-06-03 13:10 UTC, ikura-hamu commented
できました。ありがとうございます

2023-06-03 15:26 UTC, hijiki51 requested changes

2023-06-03 15:26 UTC, hijiki51 commented on docs/.vitepress/config.ts
> +    linkify: false
これもう必要ないなら戻してほしい
というかこれ他のところに影響出たりしない？(linkifyのほう)

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +なろう講習会のバックエンド用のリポジトリ、[https://github.com/traPtitech/naro-template-backend](https://github.com/traPtitech/naro-template-backend) をフォークします。リンクから GitHub のリポジトリにアクセスしてください。右上の「Fork」と書かれたボタンをクリックし、「Create
template repostioryなのでuse templateですね

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +なろう講習会のバックエンド用のリポジトリ、[https://github.com/traPtitech/naro-template-backend](https://github.com/traPtitech/naro-template-backend) をフォークします。リンクから GitHub のリポジトリにアクセスしてください。右上の「Fork」と書かれたボタンをクリックし、「Create
まえforkっていってたのはtemplateじゃなかったので

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +Task は、Go 言語で動いているタスクランナーです。これによって長いコマンドを短くできたり、複数のコマンドを 1 回で実行できたりと、開発においてとても便利なツールです。テンプレートリポジトリに`Taskfile.yaml`というファイルがありますが、このファイルによってコマンドの設定しています。公式ドキュメントは英語しかありませんが、興味のある人は目を通してみてください。
今回Go言語じゃなくてGoで統一の方針でお願いします(Hello worldも後で治します)

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +## RDBMSのインストール
必要ないならこの章削っていいかな

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +この講習会では、「Docker」と呼ばれるコンテナ型仮想環境に MariaDB を載せて使います。Docker は開発でよく使う便利なものですが、今は理解できなくても大丈夫です。今回インストールした「Docker Desktop」を立ち上げてください。これ以降もデータベースを使う作業をする際は必ず「Docker Desktop」を立ち上げてください。
Docker Desktop入れるのは今回じゃないよね（多分第一回？）

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +SQL 文は小文字でも動きます。大文字を打つのが面倒な場合は、小文字にしましょう
慣例上、わかりやすさのために大文字っていうことを書いたほうがいいかな

2023-06-03 15:26 UTC, hijiki51 commented on docs/.vitepress/config.ts
> +    linkify: false
あとline numberはデフォルトではoffのままで(1から行番号始まること少ないので)
opt-inで設定できます
https://vitepress.dev/guide/markdown#line-numbers

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +全てのカラムを取得したい場合は、`*`を使えます。
`*` (ワイルドカード)

みたいに名前を別記したほうが良いです

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +### SELECT 文
それぞれの句の最初か最後に公式ドキュメントへのリンクが欲しいです

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +sqlx ではこれを防ぐために`?`を使うことができ、SQL 文が意図しない動きをしないようになっています。
sqlxとSQLX混ざってるから統一してほしい
公式にはSQLXっぽいけど一般に使われるときはsqlxだから全部小文字でいいんじゃないかな

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/assets/files.png
yamlとyml混ざってるの気持ち悪いのでyamlに統一で

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/src/connect_db.go
> +	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=True&loc=Asia%%2FTokyo&charset=utf8mb4",
https://pkg.go.dev/github.com/go-sql-driver/mysql#Config

構造体使おう

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/src/practice_advanced.go
> +	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=True&loc=Asia%%2FTokyo&charset=utf8mb4",
同じくconfig使おう

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/src/practice_basic1.go
> +	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=True&loc=Asia%%2FTokyo&charset=utf8mb4",
同じく

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/src/practice_server.go
> +	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=True&loc=Asia%%2FTokyo&charset=utf8mb4",
同じく　

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/src/select.go
> +	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=True&loc=Asia%%2FTokyo&charset=utf8mb4",
同じく

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/src/server.go
> +	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=True&loc=Asia%%2FTokyo&charset=utf8mb4",
同じく

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/1_prepare.md
> +Task は、Go 言語で動いているタスクランナーです。これによって長いコマンドを短くできたり、複数のコマンドを 1 回で実行できたりと、開発においてとても便利なツールです。テンプレートリポジトリに`Taskfile.yaml`というファイルがありますが、このファイルによってコマンドの設定しています。公式ドキュメントは英語しかありませんが、興味のある人は目を通してみてください。
このファイルによってコマンドの設定”を”しています

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +ここからは Go 言語でデータベースを扱っていきます。`task up`を実行してデータベースが立ち上がっていることを確認してください。
```suggestion
ここからは Go でデータベースを扱っていきます。`task up`を実行してデータベースが立ち上がっていることを確認してください
```

2023-06-03 15:26 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +ここからは Go 言語でデータベースを扱っていきます。`task up`を実行してデータベースが立ち上がっていることを確認してください。
もしくは「実際にプログラムを書いて」とか

2023-06-03 15:27 UTC, hijiki51 commented
文章はほとんど問題ないです！
いくつか表記ゆれがあったのでそこだけ指摘しました。

2023-06-03 15:31 UTC, hijiki51 requested changes
正規表現周りでもう一つだけ

2023-06-03 15:31 UTC, hijiki51 commented on .textlintrc.json
> +        "/:::.*/"
これスラッシュで囲む必要ないです（というか囲むとおかしくなる）

で、たぶん$はあったほうがいいです（改行で切られると思うけど念のため）

2023-06-04 06:45 UTC, ikura-hamu commented on docs/chapter1/section4/1_prepare.md
> +なろう講習会のバックエンド用のリポジトリ、[https://github.com/traPtitech/naro-template-backend](https://github.com/traPtitech/naro-template-backend) をフォークします。リンクから GitHub のリポジトリにアクセスしてください。右上の「Fork」と書かれたボタンをクリックし、「Create
テンプレートじゃなくしちゃってたんですけど、戻した方がいいですか？
https://github.com/traPtitech/naro-template-backend

2023-06-06 03:26 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +### SELECT 文
LIMITとかOFFSETとかの句はMySQLの公式ドキュメントだと全部SELECTのページにまとめられていてリンクを持ってこれないんですけど、貼らなくてもいいですか。それとも違うページを貼った方がいですか

2023-06-06 03:36 UTC, hijiki51 commented on .textlintrc.json
> +        "/:::.*/"
正規もどきなんか、なるほどね

2023-06-06 03:36 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +### SELECT 文
アンカー使ってください

2023-06-06 03:49 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +### SELECT 文
アンカーが持ってこれないです

2023-06-06 07:13 UTC, ikura-hamu commented on docs/chapter1/section4/1_prepare.md
> +なろう講習会のバックエンド用のリポジトリ、[https://github.com/traPtitech/naro-template-backend](https://github.com/traPtitech/naro-template-backend) をフォークします。リンクから GitHub のリポジトリにアクセスしてください。右上の「Fork」と書かれたボタンをクリックし、「Create
これはどうしますか？

2023-06-06 08:12 UTC, Takeno-hito approved these changes

2023-06-06 08:12 UTC, Takeno-hito commented on docs/chapter1/section4/4_go_and_db.md
> +`code`に入っている値がただの国名コードなら問題はないのですが、`JPN' OR 1 = 1 -- `という値が入っていたらどうなるでしょうか。データベースで実行されるとき、SQL 文は下のようになります。
すごくどうでもいいけど `--` 使わずとも `JPN' OR 'A' = 'A` とかで攻撃できるので、コメントアウト使わない書き方でも良い気もします

2023-06-06 08:13 UTC, Takeno-hito requested changes
ごめん approveじゃないです

2023-06-06 08:14 UTC, ikura-hamu commented on docs/chapter1/section4/4_go_and_db.md
> +`code`に入っている値がただの国名コードなら問題はないのですが、`JPN' OR 1 = 1 -- `という値が入っていたらどうなるでしょうか。データベースで実行されるとき、SQL 文は下のようになります。
たしかに

2023-06-06 08:14 UTC, ikura-hamu commented on docs/chapter1/section4/4_go_and_db.md
> +`code`に入っている値がただの国名コードなら問題はないのですが、`JPN' OR 1 = 1 -- `という値が入っていたらどうなるでしょうか。データベースで実行されるとき、SQL 文は下のようになります。
最近までSQLのコメントアウト知らなかったから入れようと思ったけど、そもそもSQLでコメント使うことそんなにない？

2023-06-06 08:23 UTC, Takeno-hito commented on docs/chapter1/section4/4_go_and_db.md
> +`code`に入っている値がただの国名コードなら問題はないのですが、`JPN' OR 1 = 1 -- `という値が入っていたらどうなるでしょうか。データベースで実行されるとき、SQL 文は下のようになります。
SQLインジェクションの時に使います(

普通は使わんと思う

2023-06-06 08:25 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +今回は`task up`を実行したときに Adminer が立ち上がるようになっています。ブラウザで <a href='http://localhost:8080/' target="_blank" rel="noopener noreferrer">localhost:8080</a> にアクセスすると使えます。
リンク切れ判定されるけど、こうすると大丈夫。
https://github.com/traPtitech/naro-text/pull/11#issuecomment-1574887248

2023-06-06 08:35 UTC, ikura-hamu commented on docs/chapter1/section4/4_go_and_db.md
> +```sh{:no-line-numbers}
これは下の「このコマンド」が指しているもののつもりなんだけどわかりにくい？

2023-06-06 08:36 UTC, ikura-hamu commented on docs/chapter1/section4/4_go_and_db.md
> +`code`に入っている値がただの国名コードなら問題はないのですが、`JPN' OR 1 = 1 -- `という値が入っていたらどうなるでしょうか。データベースで実行されるとき、SQL 文は下のようになります。
じゃあそっちの方がシンプルなのでそっちにします

2023-06-06 09:10 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +`code`に入っている値がただの国名コードなら問題はないのですが、`JPN' OR 1 = 1 -- `という値が入っていたらどうなるでしょうか。データベースで実行されるとき、SQL 文は下のようになります。
実用上はmigrationとか書くときに使うよ（最近のトレンドだと）

2023-06-06 09:11 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +`code`に入っている値がただの国名コードなら問題はないのですが、`JPN' OR 1 = 1 -- `という値が入っていたらどうなるでしょうか。データベースで実行されるとき、SQL 文は下のようになります。
あとsqlcは使う

2023-06-06 09:11 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +`env.sh`というファイルを作り、以下の内容を書いてください。
godotenv使ったりしないといけなくて微妙かも

2023-06-06 14:38 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +### SELECT 文
あ～取れないのか・・・テキストに飛べるのでもいいが、じゃあ仕方ないです

2023-06-07 03:06 UTC, ikura-hamu commented on docs/chapter1/section4/4_go_and_db.md
> +`env.sh`というファイルを作り、以下の内容を書いてください。
exportを付ければgodotenv使わなくても、`source .env`でできそうです。

2023-06-07 03:07 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +`env.sh`というファイルを作り、以下の内容を書いてください。
exportつけるなら.shが適切（あれshellコマンドなので）

2023-06-07 03:08 UTC, ikura-hamu commented on docs/chapter1/section4/4_go_and_db.md
> +```sh{:no-line-numbers}
去年自分が`source env.sh`を忘れて動かないことが多かったのと、READEMEの基準の
> 注意事項（気をつけないと正常に実行できないことがあるもの）

には当てはまると思うんですが、どうでしょう

2023-06-07 03:09 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +```sh{:no-line-numbers}
あ～～確かにそうかも、warningでいいです

2023-06-07 03:21 UTC, ikura-hamu commented on docs/chapter1/section4/4_go_and_db.md
> +`env.sh`というファイルを作り、以下の内容を書いてください。
今回はenv.shにしますか？

2023-06-07 03:45 UTC, hijiki51 commented on docs/chapter1/section4/4_go_and_db.md
> +`env.sh`というファイルを作り、以下の内容を書いてください。
今回はそれでいいかな（`.env`のほうが適切なのはそうだけど）

2023-06-07 03:46 UTC, ikura-hamu commented
このあとチェックポイント入れます

2023-06-07 03:50 UTC, hijiki51 commented on docs/.vitepress/config.ts
> +    linkify: false
@ikura-hamu これ下のコメント見逃してそうなので

2023-06-07 03:52 UTC, ikura-hamu commented on docs/.vitepress/config.ts
> +    linkify: false
忘れてました。

2023-06-07 04:58 UTC, Takeno-hito commented on docs/chapter1/section4/2_sql.md
> +SQL 文は慣例上、わかりやすさのために大文字で書かれますが、小文字でも動きます。大文字を打つのが面倒な場合は、小文字にしましょう。
命令は慣例的に大文字だけどテーブル名カラム名はそうでもないのでその説明が欲しいかもです(後からどんどん付け足す感じになって申し訳ない)

2023-06-08 09:34 UTC, merged

2023-06-09 16:27 UTC, mehm8128 reviewed
マージしたあとでかなり申し訳ないのですが、致命的っぽそうなのもあったので確認してほしいです
致命的っぽいのは[Must]ってつけときました
他は見なくてもいいです

2023-06-09 16:27 UTC, mehm8128 commented on docs/chapter1/section4/3_sql_exercise.md
> +| ETH  | Ethiopia | Africa    | Eastern Africa |  1104300.00 |     -1000 |   62565000 |           45.2 |    6353.00 |    6180.00 | YeItyop�iya  | Republic                | Negasso Gidada |     756 |
[ややMustかも]
文字化けしてる
他にも下の方にいくつかある

2023-06-09 16:27 UTC, mehm8128 commented on docs/chapter1/section4/3_sql_exercise.md
> +このように 1 つの SQL 文の中にかっこでくくって別の SQL 文を書くような方法をサブクエリと言います。
ちょっと平仮名すぎる気がしたけどどっちでも大丈夫です

```suggestion
このように 1 つの SQL 文の中に括弧で括って別の SQL 文を書くような方法をサブクエリと言います。
```

2023-06-09 16:27 UTC, mehm8128 commented on docs/chapter1/section4/4_go_and_db.md
> +と入力して、同様に人口を表示するようにしましょう。
```suggestion
と入力したときに、指定した都市の人口を同様に表示するようにしてみましょう。
```

とかの方が分かりやすい気がする

2023-06-09 16:27 UTC, mehm8128 commented on docs/chapter1/section4/4_go_and_db.md
> +<<< @/chapter1/section4/src/select.go#main{12}
12行目強調してるのって何か意味ありますか？

2023-06-09 16:27 UTC, mehm8128 commented on docs/chapter1/section4/5_server_and_db.md
> +写真のように返ってきたら成功です。
めっちゃ細かいから無視していいけど

```suggestion
画像のように返ってきたら成功です。
```

2023-06-09 16:27 UTC, mehm8128 commented on docs/chapter1/section4/src/practice_server.go
> +	e.Start(":3000")
エラーハンドリングしてなくない？ってwarning出てたので、section3に合わせてe.Logger.Fatal()つけるとよさそう

2023-06-09 16:27 UTC, mehm8128 commented on docs/chapter1/section4/src/server.go
> +	e.Start(":3000")
こっちも

2023-06-09 16:27 UTC, mehm8128 commented on docs/chapter1/section4/src/practice_server.go
> +	e.Start(":3000")
section3に合わせて8080にした方が統一感あってよさそう

2023-06-09 16:28 UTC, mehm8128 reviewed
すみません追加です

2023-06-09 16:28 UTC, mehm8128 commented on docs/chapter1/section4/1_prepare.md
> +「Docker Desktop」を立ち上げたあと、ターミナルで `task up` を実行してください。これによってデータベースが起動します。
`task down`についてどこにも書いてなかった気がするから書いた方がよさそう

2023-06-09 16:37 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +Adminer(https://www.adminer.org/) はデータベースを GUI（マウスなど）を使って操作するためのソフトウェアです。traP 内では traQ の開発などで使われています。同じようなソフトウェアとして PHPMyAdmin などがあります。これらを使うことで SQL を使わなくてもデータベースを操作できます。
別のツールだよそれ

2023-06-09 16:38 UTC, mehm8128 commented on docs/chapter1/section4/2_sql.md
> +Adminer(https://www.adminer.org/) はデータベースを GUI（マウスなど）を使って操作するためのソフトウェアです。traP 内では traQ の開発などで使われています。同じようなソフトウェアとして PHPMyAdmin などがあります。これらを使うことで SQL を使わなくてもデータベースを操作できます。
`Adminer`ではなくて、`PHPMyAdmin`のところです

2023-06-09 16:40 UTC, hijiki51 commented on docs/chapter1/section4/2_sql.md
> +Adminer(https://www.adminer.org/) はデータベースを GUI（マウスなど）を使って操作するためのソフトウェアです。traP 内では traQ の開発などで使われています。同じようなソフトウェアとして PHPMyAdmin などがあります。これらを使うことで SQL を使わなくてもデータベースを操作できます。
ああ、下にあったのか、スマホで隠れてて見えんかった

2023-06-10 00:38 UTC, ikura-hamu commented on docs/chapter1/section4/src/practice_server.go
> +	e.Start(":3000")
サーバーは3000のイメージがあるんですけど、そんなことないですか？

2023-06-10 00:51 UTC, hijiki51 commented on docs/chapter1/section4/src/practice_server.go
> +	e.Start(":3000")
個人的にフロントは3000,バックエンドは8080のことが多い気がするが、多分そこに大した意味は無い

2023-06-10 00:54 UTC, mehm8128 commented on docs/chapter1/section4/src/practice_server.go
> +	e.Start(":3000")
前までのなろうがそうだったからかもだけど僕も↑と同じ感覚です
最近だとViteはデフォルトが5173になったり、JomonとtraPortfolioのサーバー見たみた感じ1323だったから色々ありそうだけど、section3と統一されててフロント(5173)と違っていれば大丈夫です

2023-06-10 00:57 UTC, ikura-hamu commented on docs/chapter1/section4/4_go_and_db.md
> +<<< @/chapter1/section4/src/select.go#main{12}
行ミスってました。

2023-06-10 00:59 UTC, ikura-hamu commented on docs/chapter1/section4/src/practice_server.go
> +	e.Start(":3000")
section3と統一して8080にします

2023-06-10 01:15 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +mysql> SELECT c.Name, cl.Language FROM country AS "c" JOIN countrylanguage AS "cl" ON c.Code = cl.CountryCode WHERE cl.Language = "Chinese";
僕ももう一回やったら動きませんでした。ただ、他のダブルクォーテーションのASは動いてるのでよくわかんないです。
公式ドキュメントはダブルクォーテーション使ってなかったので、無しで行こうと思います。
https://dev.mysql.com/doc/refman/8.0/ja/select.html

2023-06-10 01:18 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +mysql> SELECT c.Name, cl.Language FROM country AS "c" JOIN countrylanguage AS "cl" ON c.Code = cl.CountryCode WHERE cl.Language = "Chinese";
一応バッククオート使うと動きます

2023-06-10 01:22 UTC, ikura-hamu commented on docs/chapter1/section4/2_sql.md
> +mysql> SELECT Name, Population FROM city;
迷ったんですよね。無い方がコピペできて楽なんですけど、消しちゃって大丈夫なのか不安です