コミット粒度についてのテキスト作成
traPtitech/naro-text pull request #135
Opened 2024-05-20 13:43 UTC by mathsuky

コミット粒度についてのテキストを追加しました。確認と指摘お願いいたします:pray:

2024-05-20 14:00 UTC, mehm8128 reviewed
誤字脱字だけ

2024-05-20 14:00 UTC, mehm8128 commented on docs/chapter1/dicts/commit-size/0_index.md
> +ここからは、具体的にどのような区切りでコミットをすれば良いかということについて話します。最も一般的なのは1つの機能追加/1箇所のバグ修正につき1コミットというように、何か1つのことをなすたびにコミットをすることです。これには前述したように、変更の影響範囲を明確にしたり、レビューをやりやすくしたりという意図があります。他にも、コーディングのフォーマットやスタイルの変更やリファクタリング(コードの整
```suggestion
ここからは、具体的にどのような区切りでコミットをすれば良いかということについて話します。最も一般的なのは1つの機能追加/1箇所のバグ修正につき1コミットというように、何か1つのことをなすたびにコミットをすることです。これには前述したように、変更の影響範囲を明確にしたり、レビューをやりやすくしたりという意図があります。他にも、コーディングのフォーマットやスタイルの変更やリファクタリング(コードの整理・最適化)なども1つのコミットとして扱うこともあります。いずれにせよ、最も重要なことはチームメンバーとコミットに関するルールを共有し、それに従うことです。上記の話はあくまで基本原則であってその時の状況や開発チームの方針によって変わりうるものですから、チーム内での方針に則って進めていくことが大切でしょう。もし何かわからないことや不安なことがあれば、チームメンバーに相談することも大切です。
```

2024-05-20 14:00 UTC, mehm8128 commented on docs/chapter1/dicts/commit-size/0_index.md
> +このコミットメッセージの書き方としてはまず、変更内容が簡潔に伝わるような内容を書く必要があります。また、そのコミットが何のためにものであるかの大まかな分類(バグ修正(fix)、新機能(feat)などなど...)をコミットメッセージに含める場合もあります。より詳細な説明をする必要があれば、GitHubなどのコメント機能なども活用しましょう。コミットメッセージの書き方もチームごとに方針が決まっている
```suggestion
このコミットメッセージの書き方としてはまず、変更内容が簡潔に伝わるような内容を書く必要があります。また、そのコミットが何のためのものであるかの大まかな分類(バグ修正(fix)、新機能(feat)などなど...)をコミットメッセージに含める場合もあります。より詳細な説明をする必要があれば、GitHubなどのコメント機能なども活用しましょう。コミットメッセージの書き方もチームごとに方針が決まっている場合もあるので、チームのやり方に合わせるようにしましょう。
```

2024-05-20 14:00 UTC, mehm8128 commented on docs/chapter1/dicts/commit-size/0_index.md
> +ぜひみなさんも、よりより開発ができるよう、Gitの扱い方を少しずつ慣れていってください。
```suggestion
ぜひみなさんも、よりより開発ができるよう、Gitの扱い方に少しずつ慣れていってください。
```

2024-05-21 04:44 UTC, mathsuky commented
ご指摘ありがとうございます!一旦誤字だけ修正しました

2024-05-21 04:54 UTC, Takeno-hito requested changes
内容はすごく良いです！
must が 1 個と、何個かコメントを残しているので確認お願いします！

2024-05-21 04:54 UTC, Takeno-hito commented on docs/chapter1/dicts/commit-size/0_index.md
> +このコミットメッセージの書き方としてはまず、変更内容が簡潔に伝わるような内容を書く必要があります。また、そのコミットが何のためのものであるかの大まかな分類(バグ修正(fix)、新機能(feat)などなど...)をコミットメッセージに含める場合もあります。より詳細な説明をする必要があれば、GitHubなどのコメント機能なども活用しましょう。コミットメッセージの書き方についてもチームごとに方針が決ま
nits: コミット prefix の一覧をここに載せられると良いと思います！とりあえずほしいのは fix, feat, chore, refactor, test くらいかな

2024-05-21 04:54 UTC, Takeno-hito commented on docs/chapter1/dicts/commit-size/0_index.md
> +まず、コミットはできるだけ小さい単位で行うのが良いです。その理由としては、トラブルシューティングが容易であることが挙げられるでしょう。小さいコミットを繰り返すことにより、問題が発生した時にその原因を特定しやすくなります。また、細かい変更ごとに履歴が残るため、どの変更がどのような影響を与えたのかを簡単に追跡することができます。 加えて、チーム開発においてもメリットがあります。複数人で開発する際には
nits: めっちゃ細かい指摘だけど、じゃあ1行の方がいいの？とかなりそう 小さすぎると意味ないよ（見返しづらいし、戻したときに動かないし）とは言っておきたい

2024-05-21 04:54 UTC, Takeno-hito commented on docs/chapter1/dicts/commit-size/0_index.md
> +ここからは、具体的にどのような区切りでコミットをすれば良いかということについて話します。最も一般的なのは1つの機能追加/1箇所のバグ修正につき1コミットというように、何か1つのことをなすたびにコミットをすることです。これには前述したように、変更の影響範囲を明確にしたり、レビューをやりやすくしたりという意図があります。他にも、コーディングのフォーマットやスタイルの変更やリファクタリング(コードの整
imo: 改行・段落分けをもう少しやってほしいです！

2024-05-21 04:54 UTC, Takeno-hito commented on docs/chapter1/dicts/commit-size/0_index.md
> +Gitの基本的な内容については省略しますので、もし不安がある人は[Git講習会の資料](https://trap-jp.github.io/git-lecture-slide/slide.pdf)や[公式のドキュメント](https://git-scm.com/book/ja/v2)を読んでください
must: 文末。抜け

2024-05-21 04:54 UTC, Takeno-hito commented on docs/chapter1/dicts/commit-size/0_index.md
> +みなさんにこの後作ってもらうToDoアプリを例に考えてみましょう。もし、アプリのデザインを変更するためのブランチで作業をしているとするならば、`feat:ハンバーガーメニューを作成`や`fix:ボタンが反応しない問題を修正`のような粒度でコミットを出すと良いと思います。どちらも1つのコミットでの変更される機能は1つにとどまっていそうですし、コミットメッセージからそのコミットの役割を容易に推察する
imo: 若干細かいのですが、`feat` `fix` で新機能を追加したこと・修正したことは自明なので、 `feat: ハンバーガーメニュー` とか `fix:ボタンが反応しなかった問題` の方が良いとされていたはず。僕はこっちの方が若干好き

2024-05-21 04:54 UTC, Takeno-hito commented on docs/chapter1/dicts/commit-size/0_index.md
> +ここからは、具体的にどのような区切りでコミットをすれば良いかということについて話します。最も一般的なのは1つの機能追加/1箇所のバグ修正につき1コミットというように、何か1つのことをなすたびにコミットをすることです。これには前述したように、変更の影響範囲を明確にしたり、レビューをやりやすくしたりという意図があります。他にも、コーディングのフォーマットやスタイルの変更やリファクタリング(コードの整
fyi: 僕が説明するときは、よく「プログラムが意図した通りに動く変更の最小単位」と言っています！

2024-05-21 04:54 UTC, Takeno-hito commented on docs/chapter1/dicts/commit-size/0_index.md
> +みなさんにこの後作ってもらうToDoアプリを例に考えてみましょう。もし、アプリのデザインを変更するためのブランチで作業をしているとするならば、`feat:ハンバーガーメニューを作成`や`fix:ボタンが反応しない問題を修正`のような粒度でコミットを出すと良いと思います。どちらも1つのコミットでの変更される機能は1つにとどまっていそうですし、コミットメッセージからそのコミットの役割を容易に推察する
> `fix:ボタンが反応しない問題を修正`

nits: 修正した問題よりも、何を修正したかの方が書いてほしい気持ち なのですが受講者には全く伝わらない可能性があるのでそのままでもまぁ ok です（良いコミットメッセージ案が思いついたら変えてほしい！）

2024-05-21 04:54 UTC, Takeno-hito commented on docs/chapter1/dicts/commit-size/0_index.md
> +ここではtraPのSysAd班などで活動する人が触れることになるGitに関連する重要な内容として、コミットの粒度やコミットメッセージの付け方などについて話します。
imo: 話します→説明します

2024-05-22 12:04 UTC, mathsuky commented
たけのひとさんにいただいたレビューを反映しました。確認よろしくお願いいたします:pray:

2024-05-23 03:07 UTC, Takeno-hito approved these changes
LGTM

2024-05-30 21:49 UTC, Takeno-hito commented
コンフリクト出ちゃったので解消お願いします！

2024-06-06 13:32 UTC, merged