Refactor/setup
traPtitech/naro-text pull request #136
Opened 2024-05-23 03:26 UTC by Pugma

もろもろの環境構築を移動してきた影響で`go run {task} init`が効かなくなるなど、まだいくつか修正点はあるが一つのたたき台として

2024-05-23 03:35 UTC, hijiki51 commented
せっかくMarkdown(いやHTMLかけるのはそうなんだけど)つかってるのにHTML直書きするのはメンテ性落ちるからCode Groupsぐらいに収めてほしい

https://vitepress.dev/guide/markdown#code-groups

2024-05-23 03:38 UTC, Pugma commented
う〜ん…
やっぱり Markdown の範囲でうまくやりくりするの難しいですね
結構 OS でやること変わるんで、もうページごと分けちゃったほうがよさそうかもです

2024-06-07 05:53 UTC, alter334 requested changes
標記について変えた方が良いかも?という部分だけレビューしました
技術的な側面でまだ気づいていないミスがあったらすみません

2024-06-07 05:53 UTC, alter334 commented on docs/chapter1/section1/0_setup-windows.md
> +`Control + Shift + Command + 4`を押すと、矩形選択でスクリーンショットが撮れます。 traQ のメッセージ入力欄に`Command + V`で貼り付けられます。
macの操作になっていると思います
```suggestion
`スタート+Shift+s`を押すと、矩形選択でスクリーンショットが撮れます。 traQ のメッセージ入力欄に`Ctrl + V`で貼り付けられます。
```

2024-06-07 05:53 UTC, alter334 commented on docs/chapter1/section1/0_setup-windows.md
> +以下のサイトから使用している OS に合った VSCode のインストーラーをダウンロードして、それを実行してインストールしてください。
windowsのページならwindowsを選んで
と表記してよさそう
```suggestion
以下のサイトから`windows`の VSCode のインストーラーをダウンロードして、それを実行してインストールしてください。
```

2024-06-07 05:53 UTC, alter334 commented on docs/chapter1/section1/0_setup-windows.md
> +```
これは質問なのですがgoってlatestでバージョン指定できますか?(講習会の都合でバージョンを揃えているのならそれで大丈夫です)

2024-06-07 05:53 UTC, alter334 commented on docs/chapter1/section1/1_setup-unix.md
> +`Winキー + Shift + S`を押すと、矩形選択でスクリーンショットが撮れます。 traQ のメッセージ入力欄に`Ctrl + V`で貼り付けられます。
mac側と逆になっている?

2024-06-07 05:53 UTC, alter334 commented on docs/chapter1/section1/1_setup-unix.md
> +
とりあえず現在はasdfを使う認識でしょうか?(なんか取り除くみたいな話があったような)

2024-06-07 05:53 UTC, alter334 commented on docs/chapter1/section1/1_setup-unix.md
> +以下のサイトから使用している OS に合った VSCode のインストーラーをダウンロードして、それを実行してインストールしてください。
`macOS`を選んで と強調しても良さそう
```suggestion
以下のサイトから``macOS`の VSCodeインストーラーをダウンロードして、それを実行してインストールしてください。
```

2024-06-07 06:13 UTC, Pugma commented on docs/chapter1/section1/1_setup-unix.md
> +
nodeはasdfにまとめる方針だった気がする

2024-06-07 08:43 UTC, alter334 commented on docs/chapter1/section1/0_setup-windows.md
> +```
把握しました

2024-06-07 08:44 UTC, alter334 commented on docs/chapter1/section1/1_setup-unix.md
> +`Winキー + Shift + S`を押すと、矩形選択でスクリーンショットが撮れます。 traQ のメッセージ入力欄に`Ctrl + V`で貼り付けられます。
```suggestion
`Control + Shift + Command + 4`を押すと、矩形選択でスクリーンショットが撮れます。 traQ のメッセージ入力欄に` Command + V`で貼り付けられます。
```

2024-06-07 08:45 UTC, alter334 commented on docs/chapter1/section1/1_setup-unix.md
> +
okです

2024-06-07 08:49 UTC, alter334 approved these changes
環境構築部分のMacWindows誤表記等についての修正

2024-06-07 08:49 UTC, merged