WindowsでのGoとasdfインストール時の書き換え先を変更
traPtitech/naro-text pull request #140
Opened 2024-06-08 02:08 UTC by Pugma

確認をお願いします
close #139

2024-06-08 02:25 UTC, Takeno-hito requested changes

2024-06-08 02:25 UTC, Takeno-hito commented on docs/chapter1/section1/0_setup-windows.md
> +echo '. $HOME/.asdf/asdf.sh' >> ~/.rc
MUST: これは .bashrc のままでお願いします

2024-06-13 06:18 UTC, cp-20 approved these changes
よさそう

2024-06-13 11:56 UTC, Takeno-hito approved these changes
ごめん遅れた LGTM

2024-06-13 11:56 UTC, merged