Fix/chapter2_sec2
traPtitech/naro-text pull request #146
Opened 2024-07-12 15:11 UTC by mathsuky

本当に軽微な修正をしましたので，確認していただけると幸いです:pray:

2024-07-12 15:25 UTC, Pugma reviewed
https://router.vuejs.org/guide/essentials/dynamic-matching.html#Catch-all-404-Not-found-Route
を参考に
https://github.com/traPtitech/naro-text/pull/146/files#diff-183fb2be3fbb3c9d315928235af7d467a7c8327089ad674bdd8776753fc7d29dL17-L19
のpathマッチングの部分の最後に`*`をつけてほしいです！

2024-07-13 02:38 UTC, mathsuky commented
修正しました:kansya:

2024-07-13 04:43 UTC, Pugma requested changes
`vue-routerの設定`ページでまだパスの正規表現が直っていない部分がありそうです
修正をお願いします:pray:

2024-07-13 04:46 UTC, mathsuky commented
:dekadeka::gomen::pray_shake:

2024-07-13 04:47 UTC, mathsuky commented
今度は反省して一括置換したので大丈夫だと思います...:pray:

2024-07-13 04:52 UTC, Pugma approved these changes
見た感じオッケーです！
ルートパスマッチングの修正もありがとうございました:arigato:

2024-07-13 05:46 UTC, merged