section3 サーバーアプリケーション
traPtitech/naro-text pull request #22
Opened 2023-05-29 15:04 UTC by pikachu0310

2023-05-29 15:04 UTC, pikachu0310 commented
まだまだ超途中です

2023-05-30 02:27 UTC, Takeno-hito requested changes

2023-05-30 02:27 UTC, Takeno-hito commented on docs/chapter1/section3/2_server.md
> +$ go mod init naro-server
ここはリポジトリ名にするのが多分基本（世界中でユニークであればいいらしい？）なので、GitHub/Gitea に上げさせるつもりなら変えたいし、そうじゃなくても実際に作る時は〜って注釈を入れてほしい

2023-05-30 02:27 UTC, Takeno-hito commented on docs/chapter1/section3/2_server.md
> +`/home/userX/go/src/hello-server`というディレクトリを作成し、そのディレクトリを開きます。
mod init するなら `naro-server` のほうがよくない？

2023-05-30 02:27 UTC, Takeno-hito commented on docs/chapter1/section3/2_server.md
> +:::warning
```suggestion
:::tips
```

2023-05-30 02:27 UTC, Takeno-hito commented on docs/chapter1/section3/2_server.md
> +:::warning
ref: https://github.com/traPtitech/naro-text/blob/main/README.md

2023-05-30 02:27 UTC, Takeno-hito commented on docs/chapter1/section3/2_server.md
> +もしくは`Ctrl` + `@`でも(Windowsの場合)。
Mac でも Ctrl + @

2023-05-30 02:27 UTC, Takeno-hito commented on go.mod
> +module github.com/traPtitech/naro-text
間違えてコミットしてない？もし使うならせめてsrc下に…

2023-05-30 02:27 UTC, Takeno-hito commented on docs/chapter1/section3/2_server.md
> +    // ここを前述の通り自分のポートにすること(例: e.Start(":10100"))
あとで書くのかもしれないけど一応。ポートは好き勝手に選ばせないように（特に0~1023はウェルノウンポート）

2023-05-30 02:47 UTC, hijiki51 commented on docs/chapter1/section3/2_server.md
> +`/home/userX/go/src/hello-server`というディレクトリを作成し、そのディレクトリを開きます。
そもそもgo module使うのでgopathになくて良い

2023-06-08 12:24 UTC, pikachu0310 commented on docs/chapter1/section3/2_server.md
> +`/home/userX/go/src/hello-server`というディレクトリを作成し、そのディレクトリを開きます。
~/naro-server/hello-server という場所に作ることにします。

2023-06-08 12:28 UTC, pikachu0310 commented on docs/chapter1/section3/2_server.md
> +$ go mod init naro-server
:::warning
本来この naro-server の所にはリポジトリ名を入れることが多いです。詳しくは[公式ドキュメント](https://go.dev/doc/modules/managing-dependencies#naming_module)を参照してください。
:::
を追加しました

2023-06-08 12:34 UTC, hijiki51 commented on docs/chapter1/section3/2_server.md
> +$ go mod init naro-server
warningじゃなくてtipsかinfoで

2023-06-08 13:03 UTC, pikachu0310 commented on go.mod
> +module github.com/traPtitech/naro-text
ごめんなさい、間違えました
後で消します

2023-06-08 13:04 UTC, hijiki51 commented
これほかのとこにも書いたんですけど、今のWSLはlocalhostforwarding=Trueデフォルトで有効なのでそれでいいです

2023-06-09 07:52 UTC, pikachu0310 commented
レビューをお願いします:pray:
後半(3と4)は後でもう少しわかりやすくしようと思っています。今はもう実習編を進めている勢がいると思っているので、とりあえず早めにマージして後で修正をしたいな～と思っています。

2023-06-09 07:58 UTC, hijiki51 commented
マージを焦ると対応の手間が増えるので焦る必要はないです

2023-06-09 07:59 UTC, hijiki51 commented
直す部分はちゃんと直してください

2023-06-09 10:11 UTC, hijiki51 commented
なんかlinterちゃんと仕事してないな

2023-06-09 14:11 UTC, mehm8128 commented on docs/chapter1/section3/src/4-1_ping.go
> +	e.Logger.Fatal(e.Start(":<ポート番号>"))
ポート番号8080で固定しちゃってよさそう(去年までは共用サーバー使ってたから一人一人違う番号にしないといけなくてこういう表記にしていたので)

もしくは他の章と統一して

```suggestion
	e.Logger.Fatal(e.Start(":{ポート番号}"))
```

2023-06-09 14:13 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +`count`がない場合は 30 として，`count`が整数として解釈できない場合はステータスコードとして`400`を返してください。
1つの文で2つの「として」が別の意味で使われてるのが:yaya:

```suggestion
`count`がない場合は 30 として扱い、`count`が整数として解釈できない場合はステータスコード`400`を返してください。
```
とか？

2023-06-09 14:14 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +クエリパラメータ`count`で渡された数までの FizzBuzz を返してください。
fizzbuzzの説明ってさすがに入れなくていいかな？

2023-06-09 14:15 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +ポストされる値の足し算を返してください。
```suggestion
送信される値を足した数値を返してください。
```

2023-06-09 14:16 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +    "left": Number
好みだと思うけど、leftとright反対にしたいかも

2023-06-09 14:17 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +```javascript=
`The language 'javascript=' is not loaded, falling back to 'txt' for syntax highlighting.`ってwarningいっぱい出てる
```suggestion
```json
```

2023-06-09 14:18 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +    "left": Number
数値具体的な例で書いてもよさそう

2023-06-09 14:19 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +    {"student_number": 2, "name": "yashu"}
一応外部公開するものなので、本人に許可取ってほしいです(2人は既にtraPにいないので...)
できれば架空の名前とかにするのがよさそう

2023-06-09 14:20 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +class，studentNumber に対応する学生の情報を JSON で返してください。
```suggestion
classNumber，studentNumber に対応する学生の情報を JSON で返してください。
```

もしくはどっちもスネークケース

2023-06-09 14:21 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +自分のサーバーが正しく動作しているか確認したい方は以下の Makefile をご利用ください。
古いままなので更新するか消すか新しく書き直すかしてほしいです

2023-06-09 14:22 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +```shell=bash
`The language 'shell=bash' is not loaded, falling back to 'txt' for syntax highlighting.`

書くなら別ファイルに切り出すのがよさそう

2023-06-09 14:23 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +最後の課題のデータは次のような構造体を用意して、json.Unmarshal すると定義しやすいかも？
```suggestion
最後の課題のデータは次のような構造体を用意して、json.Unmarshal すると定義しやすいかもしれません。
```

2023-06-09 15:31 UTC, hijiki51 requested changes

2023-06-09 15:31 UTC, hijiki51 commented on docs/.vitepress/config.ts
> +  ignoreDeadLinks: [
これ mehm君が回避策見つけてるのでこのオプションいらないです

2023-06-09 15:31 UTC, hijiki51 commented on docs/.vitepress/sidebarConfigs/chapters/chapter1/sections/section3.ts
> +    link: '/chapter1/section3/1_hello-server'
0-indexでお願いします

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +今回は、Go 言語と、Go 言語の有名な web フレームワークである [Echo](https://echo.labstack.com/) を使ってサーバーアプリケーションを作っていきます。
Go 言語 => Go

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +Echo は、[Go言語の標準ライブラリ](https://pkg.go.dev/std)に入っていない外部ライブラリなので、外部からインストールしなければなりません。しかし、Go 言語にはそれを自動でやってくれる [Go module](https://go.dev/doc/tutorial/create-module) という便利な機能があるので使ってみましょう。以下を VSCode 内のタ
```suggestion
Echo は、[Go の標準ライブラリ](https://pkg.go.dev/std)に入っていない外部ライブラリなので、外部からダウンロードしなければなりません。しかし、Go にはそれを自動でやってくれる [Go module](https://go.dev/doc/tutorial/create-module) という便利な機能があるので使ってみましょう。以下を VSCode 内のターミナルで実行してください。
```

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +<span style="font-size: 150%;font-weight: bold;"> ターミナルの開き方 </span>
あとここタイトルとして強調したいだけなら単なる太字でいいです

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +go mod init naro-server
$ つけてください

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +本来この naro-server の所にはリポジトリ名を入れることが多いです。詳しくは[公式ドキュメント](https://go.dev/doc/modules/managing-dependencies#naming_module)を参照してください。
``` suggestion
本来この `naro-server` の所にはリポジトリ名を入れることが多いです。詳しくは[公式ドキュメント](https://go.dev/doc/modules/managing-dependencies#naming_module)を参照してください。
```

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +続けて、main.go を実行してサーバーを立てましょう。
```suggestion
続けて、`main.go` を実行してサーバーを立てましょう。
```

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +go run main.go
同じく$つけてください

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +```
bashでハイライトつけてください

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +```
bashでハイライトつけてください

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +```
bashでハイライトつけてください

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/2_json-response.md
> +https://go-tour-jp.appspot.com/moretypes/2
これちゃんと改行入れてください

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/2_json-response.md
> +    # Numner -> number (omitemptyは、ゼロ値の場合はそのフィールドを出力しないという意味)
でもこの説明の場合ゼロ値が正しい気がする

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/2_json-response.md
> +ダウンロードページ→ https://www.postman.com/downloads/
[]()の形にしてください

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/2_json-response.md
> +Postman を使って GET を自分のサーバーに送ってみましょう。
```suggestion
Postman を使って GET リクエストを自分のサーバーに送ってみましょう。
```

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/2_json-response.md
> +**PostmanでBodyタブを選択
1.2.3...の形にするなりして順序を明確にしてほしいです

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/4_server-exercise.md
> +クエリパラメータ`count`で渡された数までの FizzBuzz を返してください。
プログラミング基礎でやってたっけ

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/4_server-exercise.md
> +クエリパラメータ`count`で渡された数までの FizzBuzz を返してください。
やってるならいらない

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/4_server-exercise.md
> +```shell=bash
というか普通に```bashでよい

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/4_server-exercise.md
> +```shell=bash
出来ればMakefileじゃなくてshellscriptに書き換えてほしい

2023-06-09 15:31 UTC, hijiki51 commented on docs/chapter1/section3/4_server-exercise.md
> +最後の課題のデータは次のような構造体を用意して、json.Unmarshal すると定義しやすいかも？
これはtipsかinfoで囲んだほうがいいかも

2023-06-09 15:35 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +クエリパラメータ`count`で渡された数までの FizzBuzz を返してください。
やってたと思うのでいらなさそうですね

2023-06-10 02:53 UTC, pikachu0310 commented on docs/chapter1/section3/1_hello-server.md
> +#mkdirは-pを付けると、階層の深いディレクトリを1回で作れる
コードブロックの前に書くとそれはそれで見にくいので、中に入れてコメントとコマンドの間に1行改行を入れれば良いかな～と思ってます

2023-06-10 03:10 UTC, pikachu0310 commented on docs/chapter1/section3/1_hello-server.md
> +完成したら webApp/jikkyo チャンネルにスクリーンショットを投稿してください。
これだとどのタイミングで投稿すればよいかが明らかではないので、全然投稿されなさそうな気がします。どうしましょう...？

2023-06-10 03:12 UTC, hijiki51 commented on docs/chapter1/section3/1_hello-server.md
> +完成したら webApp/jikkyo チャンネルにスクリーンショットを投稿してください。
言い回しを工夫すればいいと思っていて、「講習会用のチャンネルに投稿しましょう」とかにすればいいです

2023-06-10 03:19 UTC, ikura-hamu commented on docs/chapter1/section3/4_server-exercise.md
> +クエリパラメータ`count`で渡された数までの FizzBuzz を返してください。
プログラミング基礎受けてない人昨日結構来てたので、あった方がいいと思います

2023-06-10 03:21 UTC, mehm8128 commented on docs/chapter1/section3/4_server-exercise.md
> +クエリパラメータ`count`で渡された数までの FizzBuzz を返してください。
gitについてとかHTMLについてとか、前提の講習会でやった内容は入れてないので、質問されたらサポートはするけど資料には書かないみたいな方針でいいと思います

2023-06-10 03:31 UTC, pikachu0310 commented on docs/chapter1/section3/2_json-response.md
> +:::
:::info ::: または ``` ``` かなと思うのですがどちらの方が良いですかね？とりあえずは``` ```にしようと思っています。

2023-06-10 03:40 UTC, pikachu0310 commented on docs/chapter1/section3/2_json-response.md
> +:::
![image](https://github.com/traPtitech/naro-text/assets/17543997/56d9aadc-387f-4b47-9cb7-3c10fb102244)
結局:::infoにしたのですが、良さそうでしょうか？

2023-06-10 03:42 UTC, mehm8128 commented on docs/chapter1/section3/2_json-response.md
> +:::
そうだね、とりあえずコードブロックでいい気がします

2023-06-10 03:42 UTC, mehm8128 commented on docs/chapter1/section3/2_json-response.md
> +:::
あ、被っちゃった

2023-06-10 03:43 UTC, mehm8128 commented on docs/chapter1/section3/2_json-response.md
> +:::
readmeにも書いてあるようにInfoは別の意味があるのでコードブロックにしてほしいです

2023-06-10 03:43 UTC, pikachu0310 commented on docs/chapter1/section3/2_json-response.md
> +:::
あ、:::info ::: だと文末が"。"で終わっていません。とエラーが出るので、やっぱり``` ```の方が良さそうです

2023-06-10 03:45 UTC, mehm8128 commented on docs/chapter1/section3/2_json-response.md
> +:::
それについてはなんかいくらはむくんが直してた気がする

2023-06-10 05:30 UTC, pikachu0310 commented on docs/chapter1/section3/2_json-response.md
> +ダウンロードページ→ https://www.postman.com/downloads/
このコメントはどういう意味ですか？

### Postmanのインストール
[Postman | API Development Environment](https://www.getpostman.com/) は GUI で HTTP リクエストを行えるアプリケーションです。

ダウンロードページ→ https://www.postman.com/downloads/

こう書き直したのですが、これで良さそうですか？

2023-06-10 05:30 UTC, pikachu0310 commented on docs/chapter1/section3/2_json-response.md
> +http://localhost:8080/json
先ほどの章で作成した`main.go`を、以下のように書き換えて`JSON`レスポンスを返してみましょう。

<<<@/chapter1/section3/src/2-1_json-server.go

書き換えたら、http://localhost:8080/json にアクセスして確認してみましょう。

と書き直しました:pray:

2023-06-10 07:44 UTC, pikachu0310 commented on docs/chapter1/section3/4_server-exercise.md
> +```shell=bash
shellscript書きました

2023-06-10 08:04 UTC, pikachu0310 commented
全部直しました！色々調整したり加筆したりもしました！最終的な確認をお願いします:pray::pray::pray::pray::pray:

2023-06-10 08:05 UTC, pikachu0310 commented on docs/.vitepress/config.ts
> +  ignoreDeadLinks: [
回避策見つけてるとのことなのですが、このオプションを付けないとtextlint / build (pull_request)がfailします。どうすればよいですか？

2023-06-10 12:40 UTC, pikachu0310 commented
最後の二問は、あえて答え貼ってないんですけど、良いですかね？それとも答えは載せておくべきですか？

2023-06-10 12:41 UTC, ikura-hamu commented on docs/.vitepress/config.ts
> +  ignoreDeadLinks: [
<a href='http://localhost:8080/' target="_blank" rel="noopener noreferrer">localhost:8080</a>
みたいにする

2023-06-10 14:00 UTC, mehm8128 commented on docs/chapter1/section3/1_json-response.md
> +URL: https://eo6mn2b7rlihmgg.m.pipedream.net
[Must]
ここもコードブロックにしてください

2023-06-10 14:01 UTC, mehm8128 commented on docs/chapter1/section3/2_rooting.md
> +`"hello/[ユーザー名]"`というパスのリクエストが来たときに、以下を返すサーバーを書いてみましょう。
[Must]
```suggestion
`"hello/{ユーザー名}"`というパスのリクエストが来たときに、以下を返すサーバーを書いてみましょう。
```

2023-06-10 14:01 UTC, mehm8128 commented on docs/chapter1/section3/2_rooting.md
> +Hello, [ユーザー名].
[Must]
```suggestion
Hello, {ユーザー名}.
```

2023-06-10 14:03 UTC, mehm8128 commented on docs/chapter1/section3/2_rooting.md
> +例として、Google 検索だとこんな風になってます([Google検索のパラメータ(URLパラメータ)一覧](http://www13.plala.or.jp/bigdata/google.html))
```suggestion
例として、Google 検索だとこんな風になってます([Google検索のパラメータ(URLパラメータ)一覧](http://www13.plala.or.jp/bigdata/google.html))。
```

2023-06-10 14:07 UTC, mehm8128 commented on docs/chapter1/section3/1_json-response.md
> +つまり、`HTTP Method`として`GET`を使用して、URL`http://localhost:8080/hello`にリクエストを送信しましょう。
[ややMust]
ここらへんとか他のところとかも、1つ行空ける必要ないと思うので、詰めちゃってください(どこが文のまとまりか分かりづらくて読みにくいので)
改行されないやつの対応としてやってるなら文末にスペース2つ入れた方が見た目が変わらなくていいと思います(もしくは設定変えてMDみたいにいい感じにできるならしてもらってもよさそう)

2023-06-10 14:37 UTC, pikachu0310 commented
全部修正しました、@mehm8128 確認をお願いします(軽くで良いです、レビューありがとうございました:pray::pray::pray::pray::pray:)

@hijiki51 レビュー&確認お願いします:pray::pray::pray::pray::pray:
@Takeno-hito レビュー&確認お願いします:pray::pray::pray::pray::pray:

2023-06-10 14:43 UTC, mehm8128 approved these changes
1箇所だけお願いします
あとは大丈夫そうです、対応ありがとうございました
と思ったけど、`test.sh`だけ動作確認してないので他の人に確認お願いしたいです(力尽きた)

2023-06-10 14:43 UTC, mehm8128 commented on docs/chapter1/section3/2_rooting.md
> +[Context godoc](https://golang.org/pkg/context/)
ここも行詰めた方がよさそう

2023-06-10 14:45 UTC, mehm8128 commented
> 最後の二問は、あえて答え貼ってないんですけど、良いですかね？それとも答えは載せておくべきですか？

忘れてた
足し算は基本問題だからあった方がよさそうで、発展問題はなくてもいいかも？

2023-06-10 16:54 UTC, pikachu0310 commented
ぬあああああああああああああ完成です！！！少し追加した部分があるので誰か目を通してくれると助かります。
2 changes requestedが消えなくて困ってます、もしよさそうであれば権限ある方マージしちゃってください。

2023-06-11 01:05 UTC, hijiki51 approved these changes
ちょい気になるところ（warning多用しすぎ）はあるけどcriticalじゃないので入れちゃいます

2023-06-11 01:05 UTC, merged