環境構築をアップデート
traPtitech/naro-text pull request #46
Opened 2023-06-07 03:44 UTC by hijiki51

なんかいろいろ変わってたので更新した。

Macこれでいいか確認をお願いしたいです

2023-06-07 05:03 UTC, Takeno-hito reviewed
一つだけお願いします

2023-06-07 05:03 UTC, Takeno-hito commented on docs/chapter1/section1/setup.md
> +Mac のタブを選択し、ダウンロードページに飛んで自分のアーキテクチャの pkg をダウンロード=>インストーラ起動で設定完了です。
Intel か M1/M2 かを判別する方法を追記してくれると助かります。(画面左上の🍎アイコン→｢このMacについて｣でCPUが見れます。必要そうならスクショ用意します)

2023-06-07 06:15 UTC, hijiki51 commented on docs/chapter1/section1/setup.md
> +Mac のタブを選択し、ダウンロードページに飛んで自分のアーキテクチャの pkg をダウンロード=>インストーラ起動で設定完了です。
画像と説明入れた

2023-06-07 14:05 UTC, mehm8128 commented on docs/chapter1/section1/setup.md
>  コマンドは一行づつ実行してください。
```suggestion
コマンドは一行ずつ実行してください。
```

だと思います

2023-06-08 03:05 UTC, ras0q requested changes
いくつか書きました

2023-06-08 03:05 UTC, ras0q commented on docs/chapter1/section1/setup.md
> +asdf を導入してから、その asdf を使って go を導入します。
なんか不自然だった
```suggestion
asdf を導入したのち、 asdf 経由で go を導入します。
```

2023-06-08 03:05 UTC, ras0q commented on docs/chapter1/section1/setup.md
> +インストールが終わった後に`go version`してみて`go version go1.20.5`と出れば成功です。
```suggestion
https://go.dev/doc/install
インストールが終わった後に`go version`してみて`go version go1.20.5`と出れば成功です。
```

そもそもこの書き方だとこの行までにインストールが終わっていることが前提っぽく聞こえちゃうので「目標」みたいなことを書くかcalloutで囲む(:::success?)とよさそう
asdfを使う場合はこのリンクは必要ない(一次情報なのはそうだけど別にそこまで参考にもならない)ので通常インストールのとこにだけリンク置いておくだけでよさそう

2023-06-08 03:05 UTC, ras0q commented on docs/chapter1/section1/setup.md
> +##### Golang 導入
ここ67行目ではgoに変えてるけどどっちかに統一したほうがいいかも

2023-06-08 03:05 UTC, ras0q commented on docs/chapter1/section1/setup.md
> +asdf global golang 1.20.5
いまの推奨は`plugin add`のはず
https://asdf-vm.com/guide/getting-started.html#install-the-plugin

2023-06-08 11:36 UTC, ras0q approved these changes

2023-06-08 11:51 UTC, mehm8128 reviewed
GoでHelloWorldの方、`~/go/src/hello`で作業させてますけど、git講習会で`~/develop`ディレクトリ作ったんだし`~/develop/go/hello/main.go`とかの方がいい気がします(フロントもなんでか忘れたけど`~/vue`で作業させてたけど`~/develop/vue`とかにします)

2023-06-08 11:51 UTC, mehm8128 commented on docs/chapter1/section1/setup.md
> +:::
これ文字として表示されちゃってるので消してよさそうです(バグっぽそうですが)

2023-06-08 11:52 UTC, hijiki51 commented
GOPATHになっちゃってるのは誰かやってくれ～～～（ちょっと今余裕がない）

2023-06-08 11:54 UTC, hijiki51 commented
@mehm8128 修正した

2023-06-08 11:54 UTC, mehm8128 commented
そういえば前に言ってた気がしますね...
別PRでやっときます

2023-06-08 12:02 UTC, mehm8128 approved these changes
よさそうです！

2023-06-08 12:03 UTC, merged