Node.jsのインストール、SSH鍵登録
traPtitech/naro-text pull request #53
Opened 2023-06-09 13:28 UTC by mehm8128

書きました。確認お願いします

- SSH鍵上書きされてしまう可能性があるのをwarningにするべきかdangerにするべきか
- 手元でWSLのasdfなしNode.jsインストールしてみたら20.3.0じゃなくて20.2.0インストールされちゃったのですがどうしましょう
- macの環境構築ちょっと怪しいのでmacの人見てほしいです(`brew install node`したとき、元のなろうの資料にはPATH通すコマンドが表示されるとか書いてあったけど手元のWSLでbrew入れてやってみたら出なかったのでそこらへん気になってます)

2023-06-09 14:01 UTC, mehm8128 commented
はあくしました

2023-06-09 14:13 UTC, mehm8128 commented
フォーマットかけたりするの忘れてた
あとでやります

2023-06-09 14:49 UTC, nokhnaton approved these changes
ありがとうございます。ほとんど良いと思うのですが、Mustache構文がうまく理解できない人も多そうな雰囲気なので、軽く説明載せてもいいと思います。
以下説明文の案です

`{ユーザー名}`のように書かれている部分は`{}`を取り除いた上で内部の説明に書かれている内容を入れてください。
詳しい情報が欲しい場合はMustache構文などで検索すると良いと思います

2023-06-09 15:12 UTC, mehm8128 commented
ちょっと変えてみました
「Mustache構文」とやらは聞いたことなかったのと、調べてもあんまりしっくりこなかったので書かないことにしました

2023-06-09 15:18 UTC, hijiki51 requested changes

2023-06-09 15:18 UTC, hijiki51 commented on docs/chapter1/section2/0_vue-intro.md
> +todo
ここTODOのままだけど

2023-06-09 15:19 UTC, mehm8128 commented on docs/chapter1/section2/0_vue-intro.md
> +todo
PRの説明に書いてある通りです

2023-06-09 15:33 UTC, hijiki51 commented on docs/chapter1/section2/0_vue-intro.md
> +todo
> macの環境構築ちょっと怪しいのでmacの人見てほしいです(brew install nodeしたとき、元のなろうの資料にはPATH通すコマンドが表示されるとか書いてあったけど手元のWSLでbrew入れてやってみたら出なかったのでそこらへん気になってます)

これ？怪しいってことじゃなくてわかんないってことか

2023-06-09 15:34 UTC, hijiki51 commented on docs/chapter1/section2/0_vue-intro.md
> +todo
ああ、理解した

2023-06-09 15:34 UTC, hijiki51 commented on docs/chapter1/section2/0_vue-intro.md
> +todo
とりあえず古いやつそのまま移植してほしい（マージできないので）

2023-06-09 15:36 UTC, mehm8128 commented on docs/chapter1/section2/0_vue-intro.md
> +todo
あーそうですね
分かりました、一旦そのまま移します

2023-06-09 15:39 UTC, mehm8128 commented on docs/chapter1/section2/0_vue-intro.md
> +todo
しました

2023-06-10 03:04 UTC, hijiki51 approved these changes

2023-06-10 03:14 UTC, merged