Fix section4
traPtitech/naro-text pull request #61
Opened 2023-06-10 09:29 UTC by ikura-hamu

2023-06-10 09:36 UTC, ikura-hamu commented
#56 #57

2023-06-11 00:55 UTC, hijiki51 requested changes

2023-06-11 00:55 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
ASDFで入れてるなら`asdf reshim `か`asdf reshim golang`です

2023-06-11 00:55 UTC, hijiki51 commented on docs/chapter1/section4/1_sql.md
> +``SELECT {カラム名} AS `{別名}` FROM {テーブル名};``で、カラムに別名を付けて扱うことができます。
これ別にbackquoteつけなくても行けるはずだけどつける理由なんだっけ？

単純にカラム名と被るっていうなら、それは別名を変えたほうがいいし、それはちゃんと伝えるべき

2023-06-11 00:55 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
生で入れてるなら逆にこれしなくていい

2023-06-11 07:02 UTC, ikura-hamu commented on docs/chapter1/section4/1_sql.md
> +``SELECT {カラム名} AS `{別名}` FROM {テーブル名};``で、カラムに別名を付けて扱うことができます。
練習問題で`Rank`という別名付けさせようとしたんですけど、関数の`RANK()`があって動かなかったので全部つけるようにしました。基本無しで行って、その問題だけヒントというか注釈というかをつけようと思います。

2023-06-11 07:54 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
DockerでUbuntu立てて試したんですが、asdfで入れた場合ははreshimしたら使えるようになるのは確かめました。そのまま入れた場合は`go install`でtaskを入れる先が`$GOPATH/bin`になり、`GOPATH`のデフォルト値が`$HOME/go`なので、パスが通ってない感じです。

2023-06-11 07:57 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
`mv $(go env GOPATH)/bin/task /usr/local/go/bin`をしてあげると大丈夫そうですが、もうちょっときれいなやり方ありますかね

2023-06-11 08:07 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
$GOBINって変数なかったっけ

2023-06-11 08:08 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
が、生で入れた場合は`~/.basrc`がただしいね（通らなかったら）

2023-06-11 08:09 UTC, hijiki51 commented on docs/chapter1/section4/1_sql.md
> +``SELECT {カラム名} AS `{別名}` FROM {テーブル名};``で、カラムに別名を付けて扱うことができます。
注釈つけるのはそうなんだけど、回避策がbackquote名のわかりにくいからrankじゃなくてほかの単語にしない？

2023-06-11 08:12 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
`$GOBIN`は存在しますけど、デフォルト空ですね

2023-06-11 08:12 UTC, ikura-hamu commented on docs/chapter1/section4/1_sql.md
> +``SELECT {カラム名} AS `{別名}` FROM {テーブル名};``で、カラムに別名を付けて扱うことができます。
`Ranking`とかですか？

2023-06-11 08:20 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
生で入れて`task`が実行できなかったら、`~/.bashrc`で`PATH`に追加するでいいですか？

2023-06-11 08:20 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
でもこれだとHOME/goができちゃって気持ち悪いんですけど、そんなことないですかね

2023-06-11 08:23 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
や、$GOBINってbinのインストール先を設定する環境変数でそこを書き換えることができるねって意味だった

2023-06-11 08:23 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
まあただめんどいのはそう

2023-06-11 08:23 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
> でもこれだとHOME/goができちゃって気持ち悪いんですけど、そんなことないですかね

いいんじゃないかな・・・（そういうものだし）

2023-06-11 08:24 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
$HOME/goでも$GOBINでも結局~/.bashrcには書くので好きなほうで

2023-06-11 08:25 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
asdfで入れてる場合と生で入れてる場合で`task init`を分けて、生の方はGOBINの設定をしてからtaskインストールが一番いい気もします

2023-06-11 08:33 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
そこに書くのはめんどいぞ・・・

2023-06-11 08:33 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
せめてやるなら`task init:raw`みたいな分け方するほうがまし

2023-06-11 08:33 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
というか$GOBINを.bashrcに書かせるのってそんな手間かな？

2023-06-11 08:34 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
`echo 'export GOBIN=/usr/local/bin >> ~/.bashrc`でいいと思うんだけど

2023-06-11 08:37 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
全部initで済ませられたら楽なのでそうしようと思っただけです。

2023-06-11 08:38 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
生は環境差異が地獄なのでおとなしく書かせたほうがいいと思います

2023-06-11 08:38 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
生で入れた人は
1. ↑↑を実行
2. `source ~/.bashrc`
3. `task init`
4. `source ~/.bashrc`

になりますか

2023-06-11 08:40 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
そもそもなんか認識違くない？
go run ~~task/cmd@latestでやるからgo installはtask initの時に行われるよ

2023-06-11 08:40 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
だからバイナリはいるのはtask initの後

2023-06-11 08:41 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
認識はあってそうですけど…

2023-06-11 08:41 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
だから、
1. `go run ~~/task/cmd@latest init`
2. `echo 'export GOBIN=/usr/local/bin' >> ~/.bashrc`(bashrcだったりzshrcだったりするから注意)
3. `source ~/.bashrc`

2023-06-11 08:42 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
あ、そっかPATHじゃないや

2023-06-11 08:42 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
あ、みすってますね

2023-06-11 08:42 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
ikura-hamu君の出会ってます

2023-06-11 08:42 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
ただ最後のがいらないです

2023-06-11 08:42 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
だから、

1. `echo 'export GOBIN=/usr/local/bin' >> ~/.bashrc`(bashrcだったりzshrcだったりするから注意)
2. `source ~/.bashrc` 
3. `go run ~~/task/cmd@latest init`

2023-06-11 08:43 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
`task init`でやるのはtaskのインストールだけにして、生で入れた人はその前にGOBINについてbashrcに書く。
でいいですか？

2023-06-11 08:45 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
で、いいと思う

2023-06-11 08:45 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
だれかほかに五件ある人いれば（インストール先のパスとかここ微妙かもしれない）

2023-06-11 08:54 UTC, ras0q commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
調べてないけどGOBINを/usr/local/binにするのちょっと違和感ある
普通はやっぱり~/go/binのはずだし

2023-06-11 08:56 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
よくよくかんがえたら生で入れたら~/goは問答無用でできます（モジュール保存先がそこなので）

2023-06-11 08:56 UTC, hijiki51 commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
> 普通はやっぱり~/go/binのはずだし

そもそもこれgo moduleがない時代の遺産だと思ってる

2023-06-11 08:59 UTC, ras0q commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
てかtask initの中でパスの追加をしてるのが微妙だと思ってて、手動で.bashrcに書いてからtask実行じゃダメですか？

2023-06-11 09:00 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
それをやるようにするつもりです

2023-06-11 09:02 UTC, ras0q commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
> `task init`でやるのはtaskのインストールだけにして、生で入れた人はその前にGOBINについてbashrcに書く。 でいいですか？

これか、見逃してました:pray:

2023-06-11 09:04 UTC, ras0q commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
自分はGOBINについては書かずに`export PATH=$PATH:$(go env GOPATH)/bin`を.bashrcに追加するのが一番無難かなって思いました

2023-06-11 09:12 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
GOBINを/usr/local/go/binにすればgoのインストールでパスを通してるのでそれだけで使えるんですけど、これはあんまりしない感じですかね

2023-06-11 09:15 UTC, ras0q commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
1. パスが通ってるところにgo入れる
2. `$(go env GOPATH)/bin`をPATHに追加する
3. `go install`で入れたツールが使えるようになる

が一般的だと思ってます:tabun:
どうせGOBINを設定するならデフォルトのインストールパスをPATHに追加したいかな(自分の環境見たらGOBIN空だった)

2023-06-11 09:20 UTC, ikura-hamu commented on docs/chapter1/section4/0_prepare.md
> +`go run github.com/go-task/task/v3/cmd/task@latest init`をコマンドラインで実行してください。実行が終わったら`source ~/.bashrc`をコマンドラインで実行します。
今回そもそもGoを入れてからそこにパスを通してますね

2023-06-12 01:38 UTC, ikura-hamu commented
https://github.com/traPtitech/naro-template-backend と合わせて確認お願いします。

2023-06-13 00:05 UTC, hijiki51 approved these changes

2023-06-13 00:16 UTC, merged