chapter2 section4 Docker
traPtitech/naro-text pull request #83
Opened 2023-07-07 09:30 UTC by ikura-hamu

Dockerについて
https://md.trap.jp/N9lo0TSQRFyHDxny_xYITw

2023-07-07 09:37 UTC, ikura-hamu commented
dockerコマンドとりあえず以前の資料にあったやつを書いたんですが、これ以外で書いた方がいいやつあったら教えてください。

2023-07-07 13:06 UTC, hijiki51 requested changes
- Dockerfileの書き方
- docker compose(v2) の簡単な紹介（この章と同じぐらいの温度でいい）& compose.yamlの書き方

について書いてほしいです

2023-07-07 13:06 UTC, hijiki51 commented on docs/chapter2/section4/0_commands.md
> +まずは Doker Desktop が起動している状態で、このコマンドを実行してください。
Docker

2023-07-08 03:25 UTC, ikura-hamu reviewed
今までの資料はマルチステージビルドについて書いてあったんですが、書いた方がいいですか。

2023-07-08 04:09 UTC, hijiki51 commented
余裕があればでいいです（知っておいたほうがいいのはそうだけど、まあ必須ではないかなという気持ち）

2023-07-08 04:14 UTC, hijiki51 requested changes

2023-07-08 04:14 UTC, hijiki51 commented on docs/chapter2/section4/1_image.md
> +RUN apk add --update --no-cache ca-certificates git
別にここ軽量化する必要ないのでbookwormでいい気がする

2023-07-08 05:07 UTC, ikura-hamu commented on docs/chapter2/section4/1_image.md
> +RUN apk add --update --no-cache ca-certificates git
[1.20.5-bookworm](https://github.com/docker-library/golang/blob/72bc141d781ae54ef20f71aa1105449cb6c2edc4/1.20/bookworm/Dockerfile) を使うってことで合ってますか？

2023-07-08 05:11 UTC, hijiki51 commented on docs/chapter2/section4/1_image.md
> +RUN apk add --update --no-cache ca-certificates git
そうですね（Debian系のがわかりやすいかなと）

2023-07-08 05:12 UTC, hijiki51 commented on docs/chapter2/section4/1_image.md
> +RUN apk add --update --no-cache ca-certificates git
あとalpine、muslあたりで変なの踏んだらいやだなと

2023-07-08 05:17 UTC, ikura-hamu commented on docs/chapter2/section4/1_image.md
> +RUN apk add --update --no-cache ca-certificates git
```Dockerfile
FROM golang:bookworm

WORKDIR /work

COPY . .

RUN go build -o app

ENTRYPOINT ./app
```

これでイメージ1GBになっちゃったんですけど、いいですかね

2023-07-08 05:20 UTC, hijiki51 commented on docs/chapter2/section4/1_image.md
> +RUN apk add --update --no-cache ca-certificates git
そんなdebianでかかったっけ、:w:

2023-07-08 05:23 UTC, hijiki51 commented on docs/chapter2/section4/1_image.md
> +RUN apk add --update --no-cache ca-certificates git
じゃあ壊れないことを祈ってalpineに戻してください、あとapk install ってなくても動かなかったでしたっけ

2023-07-08 05:26 UTC, ikura-hamu commented on docs/chapter2/section4/1_image.md
> +RUN apk add --update --no-cache ca-certificates git
戻しました。apk installは無くても動きました

2023-07-11 07:29 UTC, ikura-hamu commented
prettier走らせようとすると`No parser could be inferred for file: docs/chapter2/section4/src/ex2-greeting1.conf`って言われるんですけど、どうしたらいいんでしょう。

2023-07-11 13:02 UTC, hijiki51 commented
`.prettierignore`を設定すればよいです
https://prettier.io/docs/en/ignore.html

2023-07-11 13:58 UTC, ras0q commented
> .prettierignoreを設定すればよいです

適切に.mdだけを見るコマンドに設定する方が本質な気がする

2023-07-11 14:40 UTC, hijiki51 commented
prettierignoreはtextlintじゃないよ

2023-07-11 14:41 UTC, hijiki51 commented
いや普通にprettierignoreで!*.js、!*.tsにすればいい

2023-07-11 14:42 UTC, ras0q commented
allowlist方式で書くならそもそも`npm run fmt`を
```diff
- "fmt": "prettier --check docs",
+ "fmt": "prettier --check docs/**/*.{js,ts,vue}",
```
にするべきじゃない？

2023-07-18 01:41 UTC, Takeno-hito requested changes
大体いい感じだと思います。細かいところが多いですが修正をお願いします

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/0_commands.md
> +mkdir html && cd html
これホームディレクトリでやっちゃいそうな人いると思うから、どこでもできるということを書いておいてもいいかも

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/0_commands.md
> +確認出来たらコンテナを停止、削除しましょう。
```suggestion
確認出来たらコンテナの停止、削除をしましょう。
```
もしくは
```suggestion
確認出来たらコンテナの停止し、削除しましょう。
```

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/1_image.md
> +今までは`go run`コマンドでプログラムを実行していましたが、Go では`go build`コマンドでコンパイルして実行ファイルを生成し、それを実行できます。
あんま良い書き方は思いついてないけど、「それを実行できます」は変えたい気持ちがあります

```suggestion
今までは`go run`コマンドでプログラムを実行していましたが、Go では`go build`コマンドでコンパイルして実行ファイルを生成し、実行ファイルを用いてプログラムを実行できます。
```

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +`docker-compose.yml`というファイルに設定を書き、`docker compose {操作} [オプション]`のようなコマンドを入力することで使えます。
docker v2 だと `compose.yml` が標準らしいです（この前指摘された）

既に色んなところが docker-compose.yml になっているのでだいぶ手遅れ気味な気もしますが、僕はこの章だけでも `compose.yml` にした方が良いかなと思っています

ref: https://zenn.dev/miroha/articles/whats-docker-compose-v2#compose%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E5%90%8D%E5%89%8D

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +yaml ファイルは、インデントでオブジェクト(ひとまとまりの情報)を表現します。
yaml ファイルなのに `.yaml` じゃなくて `.yml` なの？って疑問を持たれそうなのでちょっと補足挟んでもいいかも？

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +`-d`オプションを追加することで、デーモン（バックグラウンド）で起動できます。実際のサーバーなどで運用する場合はバックグラウンドで起動することになります。
デタッチモードでは？少し自信がないので調べてほしいけど

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +コンテナを一括で停止・削除するためには、`down`を実行します。
`logs`> `exec` >>> `start` = `stop` もほしいかも。並び順はほしい順

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +nginx の設定ファイルとして、**`server/nginx/conf.d/greeting.cnf`** を下のように書きます。
これ `server/` はだいぶ深い所まで行っている気がしますがあっていますか？(compose.yml も server 下にある？)

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/src/docker-compose-nginx.yml
> +  greeting:
nginx で使うなら ホスト名明示しておきたいかも

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/src/ex2-greeting1.conf
> +	proxy_set_header    Host    $host;
hard / soft tab が混ざってそうです

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +<<< @/chapter2/section4/src/greeting.conf{txt}
相対パス・絶対パスの話を盛り込んでもいいかも ホームディレクトリの話と ../ までしちゃう？

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +`greeting`コンテナは nginx 経由のアクセス経路を作ったので、ポートの開放設定を消しています。`reverse_proxy`コンテナのコンテナ側ポートが`80`なのは、 nginx のデフォルトの設定がそうなっているからです。
- nginx のデフォというか http プロトコルのデフォが 80 だからな気がしないでもない。 
- listen するポートを変える方針でも良い気もしています（こっちはオプションなのでどっちでも良い）

2023-07-18 01:41 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +curl -H "Host:hello.local" http://localhost:3000/greeting
最終的にどういう経路で通信が来ているか書いてもいいかも

2023-07-18 01:48 UTC, hijiki51 commented on docs/chapter2/section4/0_commands.md
> +Docker を扱う上でよく使うコマンドを紹介していきます。基本的には`docker [リソース] {操作} [オプション] {対象}`のような構成になっています。
いやこれであってます
`docker network create`なので

2023-07-18 01:50 UTC, hijiki51 commented on docs/chapter2/section4/1_image.md
> +今までは`go run`コマンドでプログラムを実行していましたが、Go では`go build`コマンドでコンパイルして実行ファイルを生成し、それを実行できます。
↑にするなら "その"ファイルを用いて～か、"生成された"実行ファイルを用いて～のほうがいいかも

2023-07-18 01:51 UTC, hijiki51 commented on docs/chapter2/section4/2_compose.md
> +`docker-compose.yml`というファイルに設定を書き、`docker compose {操作} [オプション]`のようなコマンドを入力することで使えます。
~~なんならymlじゃなくてyamlにしたい気持ちも~~

2023-07-18 01:51 UTC, hijiki51 commented on docs/chapter2/section4/2_compose.md
> +yaml ファイルは、インデントでオブジェクト(ひとまとまりの情報)を表現します。
yamlにしちゃっていいんじゃない？

2023-07-18 01:53 UTC, hijiki51 commented on docs/chapter2/section4/2_compose.md
> +`-d`オプションを追加することで、デーモン（バックグラウンド）で起動できます。実際のサーバーなどで運用する場合はバックグラウンドで起動することになります。
```
 -d, --detach                         Run container in background and print container ID
```

2023-07-18 01:54 UTC, hijiki51 commented on docs/chapter2/section4/2_compose.md
> +コンテナを一括で停止・削除するためには、`down`を実行します。
まあここら辺はトラブルシューティングで使うやつなのでこの講習ではなくてもいい気がする（若干すでに重いので）

2023-07-18 01:54 UTC, hijiki51 commented on docs/chapter2/section4/2_compose.md
> +コンテナを一括で停止・削除するためには、`down`を実行します。
まあここら辺はトラブルシューティングで使うやつなのでこの講習ではなくてもいい気がする（若干すでに重いので）

2023-07-18 01:55 UTC, hijiki51 commented on docs/chapter2/section4/2_compose.md
> +`greeting`コンテナは nginx 経由のアクセス経路を作ったので、ポートの開放設定を消しています。`reverse_proxy`コンテナのコンテナ側ポートが`80`なのは、 nginx のデフォルトの設定がそうなっているからです。
> nginx のデフォというか http プロトコルのデフォが 80 だからな気がしないでもない。

そうです。https使うときはちゃんと443をlistenするはず

2023-07-18 01:56 UTC, hijiki51 commented on docs/chapter2/section4/2_compose.md
> +コンテナを一括で停止・削除するためには、`down`を実行します。
とはいえlogsはあってもいいな

2023-07-19 05:01 UTC, ikura-hamu commented on docs/chapter2/section4/0_commands.md
> +Docker を扱う上でよく使うコマンドを紹介していきます。基本的には`docker [リソース] {操作} [オプション] {対象}`のような構成になっています。
`docker [リソース] {操作} [オプション] {対象}`なのはそうなんですけど、ほとんど省略形で紹介してしまったので、微妙ですね。去年までの資料だと`docker continer run {イメージ名}`とかもあったんですが、使わないので削除しちゃってました

2023-07-19 05:04 UTC, ikura-hamu commented on docs/chapter2/section4/0_commands.md
> +mkdir html && cd html
ぼく全然ホームディレクトリで作業するんだけど、もしかして少数派？

2023-07-19 05:09 UTC, ikura-hamu commented on docs/chapter2/section4/2_compose.md
> +`docker-compose.yml`というファイルに設定を書き、`docker compose {操作} [オプション]`のようなコマンドを入力することで使えます。
公式でも`docker-compose.yml`で書いてるところもあってたまたまそこ見てました。`compose.yaml`に直しておきます。
https://docs.docker.com/compose/gettingstarted/

2023-07-19 05:11 UTC, ikura-hamu commented on docs/chapter2/section4/2_compose.md
> +`-d`オプションを追加することで、デーモン（バックグラウンド）で起動できます。実際のサーバーなどで運用する場合はバックグラウンドで起動することになります。
前回の資料信じちゃった

2023-07-19 05:17 UTC, ikura-hamu commented on docs/chapter2/section4/2_compose.md
> +nginx の設定ファイルとして、**`server/nginx/conf.d/greeting.cnf`** を下のように書きます。
資料がいろいろごっちゃになっちゃってそう。前のページで作ったnaro_serverディレクトリで、nginxフォルダを作ってもらう意図

2023-07-19 05:18 UTC, ikura-hamu commented on docs/chapter2/section4/2_compose.md
> +<<< @/chapter2/section4/src/greeting.conf{txt}
もしかして今まで一度も触れられてない？

2023-07-19 06:12 UTC, ikura-hamu commented on docs/chapter2/section4/0_commands.md
> +Docker を扱う上でよく使うコマンドを紹介していきます。基本的には`docker [リソース] {操作} [オプション] {対象}`のような構成になっています。
docker [リソース] {操作} [オプション] {対象}なのはそうなんですけど、ほとんど省略形で紹介してしまったので、微妙ですね。去年までの資料だとdocker continer run {イメージ名}とかもあったんですが、使わないので削除しちゃってました

2023-07-19 06:12 UTC, ikura-hamu commented on docs/chapter2/section4/0_commands.md
> +mkdir html && cd html
ぼく全然ホームディレクトリで作業するんだけど、もしかして少数派？

2023-07-19 06:15 UTC, ikura-hamu commented on docs/chapter2/section4/2_compose.md
> +`docker-compose.yml`というファイルに設定を書き、`docker compose {操作} [オプション]`のようなコマンドを入力することで使えます。
公式でもdocker-compose.yml使ってるところがあってそこ見てました。直しておきます

https://docs.docker.com/compose/gettingstarted/

2023-07-19 06:27 UTC, ikura-hamu commented on docs/chapter2/section4/src/docker-compose-nginx.yml
> +  greeting:
あまり指定するメリットを感じないんだけど、よくある事例？

2023-07-19 06:37 UTC, ikura-hamu commented on docs/chapter2/section4/0_commands.md
> +Docker を扱う上でよく使うコマンドを紹介していきます。基本的には`docker [リソース] {操作} [オプション] {対象}`のような構成になっています。
省略形とかも載せていい感じに説明します。

2023-07-21 00:05 UTC, Takeno-hito commented on docs/chapter2/section4/0_commands.md
> +mkdir html && cd html
ホームディレクトリに `naro-workshop` みたいなディレクトリも作ってないってこと？

2023-07-21 00:07 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +コンテナを一括で停止・削除するためには、`down`を実行します。
db のアクセスで exec 使うので exec までほしい気持ちもありつつ、多すぎるからなくても良いと思いつつという感じです　とりあえず乗せて多かったら tips に動かすとかでも良いかもしれない？

2023-07-21 00:26 UTC, Takeno-hito commented on docs/chapter2/section4/src/docker-compose-nginx.yml
> +  greeting:
あんまり深い意味はなくて、単純に指定しておいた方が始めて学習するときにわかりやすいかなと思ったくらいです。別に指定しなくても良いといえば良いと思う？

2023-07-21 00:28 UTC, Takeno-hito commented on docs/chapter2/section4/2_compose.md
> +<<< @/chapter2/section4/src/greeting.conf{txt}
もしかしたらそうかも？今まですべて相対パスで説明してたし `../` も使ってなかったから特に説明はいらなかったかもだけど、今回は絶対パスを使ってるから

2023-07-21 01:28 UTC, mehm8128 commented on docs/chapter2/section4/2_compose.md
> +<<< @/chapter2/section4/src/greeting.conf{txt}
プログラミング基礎講習会でやってると思ってたけどやってないんだっけ
軽くテキスト見た感じ、`../`はやってた(去年まではなろうの第1回か2回くらいで説明してた)

2023-07-21 01:28 UTC, mehm8128 commented on docs/chapter2/section4/0_commands.md
> +mkdir html && cd html
最初のVueの回でdevelop以下を指定したからその後もそこでやってくれてると思ってるけどそうでもないのかな

2023-07-21 07:59 UTC, ikura-hamu commented on docs/chapter2/section4/0_commands.md
> +mkdir html && cd html
最近「ディレクトリ分けたらきれいになるんじゃね？」と思ってちょっとだけ分けた。大発見だと思ってたのに違うのね、

```
ikura-hamu@Laptop-hk:~$ ls ~
CodeTest                  h23s_01               isucon                 questions          traQ
Competitive               h23s_01_practice      miyagi-2023            shell-traq         trap-collection-server
GitHub_README             hackathon_22_spring   naro-template-backend  springin-workshop  ute-1
bot_ikura-hamu            html                  naro22                 tools              z_sandbox
creators-conference-2023  ikura-hamu_portfolio  naro23
```

2023-07-21 07:59 UTC, ikura-hamu commented on docs/chapter2/section4/0_commands.md
> +mkdir html && cd html
「自分が作業したいところで」とか足しときます

2023-07-21 09:19 UTC, pikachu0310 commented on docs/chapter2/section4/0_commands.md
> +
https://docs.docker.jp/engine/reference/commandline/run.html が二個あるけどこれは正常ですか？

2023-07-22 03:05 UTC, Takeno-hito approved these changes
直前になってごめんなさい、ざっくり見直しましたが多分大丈夫でしょう。完璧には見れてないので、もしかしたらほかと同様に後から修正をお願いするかもしれません。

2023-07-22 03:51 UTC, merged