2部1章
traPtitech/naro-text pull request #85
Opened 2023-07-11 08:18 UTC by nokhnaton

2023-07-14 02:25 UTC, Takeno-hito requested changes
一旦先頭40行だけ。一回文章の文体を見直してほしいです

2023-07-14 02:25 UTC, Takeno-hito commented on docs/chapter2/section1/0_server_setup.md
> +54 行目の`e.Use(session.Middleware(store))`が echo にこのセッションストアを使ってと言っている部分です。
54 ではなくない？

2023-07-14 02:25 UTC, Takeno-hito commented on docs/chapter2/section1/0_server_setup.md
> +# main.go
ここ要修正

2023-07-14 02:25 UTC, Takeno-hito commented on docs/chapter2/section1/0_server_setup.md
> +セッションストアを設定しています。セッションは HTTP リクエストを送ってきた User が誰かを確認するために使うのですが、それらを覚えておくための場所を用意しているイメージです(ちょい雑な気がする)
- セッションは新出単語なのである程度説明をしてほしい
- ユーザーのセッションの一覧をDBに保存していると説明すれば十分じゃないですか？
- 引数について軽く説明して上げると良いと思います

2023-07-14 02:25 UTC, Takeno-hito commented on docs/chapter2/section1/0_server_setup.md
> +それ以降では echo についての設定をしています。具体的にはハンドラの登録やサーバーの起動などを行っています。ここら辺は知っていると思っております。
```suggestion
それ以降では echo についての設定をしています。具体的にはハンドラの登録やサーバーの起動などを行っています。このあたりは第一部で説明しているはずなので割愛します。
```

2023-07-14 02:25 UTC, Takeno-hito commented on docs/chapter2/section1/0_server_setup.md
> +基本的に Password を平文で保存しておくのは危険です！　従って、パスワードを DB に格納するときはハッシュ化を行ってから格納します。(ハッシュ化については調べてください)
```suggestion
Password は平文で保存してはいけません！パスワードを DB に格納するときはハッシュ化を行ってから格納してください。
```

ハッシュ化はスライドに入ってませんか？

2023-07-14 02:25 UTC, Takeno-hito commented on docs/chapter2/section1/0_server_setup.md
> +<<<@/chapter2/section1/src/0/main.go#hash{go:line-numbers}
ハッシュ化の恩恵が薄くなってしまうので、ハッシュソルトを入れてほしいです。

2023-07-14 03:21 UTC, mehm8128 requested changes
方針だけ書きました

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/0_server_setup.md
> +:::
今回はローカルでやってるのでできません

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/0_server_setup.md
> +:::info
確か演習はinfoとかで囲うんじゃなくて見出しつけるんじゃなかったっけ
他の章と揃えるようにしてください

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/0_server_setup.md
> +<<<@/chapter2/section1/src/0/main.go{go:line-numbers}
最初に一気にコード提示されるの、かなりうわぁってなるので関数ごとに少しずつ書いていって最後に全体のコード提示するのがいい気がしてます

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/1_router-setup.md
> +:::warning
warningではなさそう

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/1_router-setup.md
> +:::tip
tipというよりwarningな気がする？他のところもREADME見て考え直してほしいです

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/1_router-setup.md
> +# プロキシの設定
ここプロキシよりサーバーでCORSの設定した方がいい気がするのですがどうですか

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/2_axios.md
> +以前の講習会でも使った RequestBin を使って API を叩く練習をしてみましょう。
>以前の講習会でも使った

普通に気になっただけなんだけど、これどこかで使ってたっけ

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/2_axios.md
> +delete は若干特殊で`{data: {}}` とすれば`data`の中身が投げられます。
deleteでbody使うのあんまりしないのでやめた方がよさそう

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/2_axios.md
> +### src/pages/CityPage.vue
他のところもだけど、TS対応忘れずにお願いします

2023-07-14 03:21 UTC, mehm8128 commented on docs/chapter2/section1/2_axios.md
> +:::tip
こことかも演習問題はtipじゃなくて見出しにするようにしてください

2023-07-14 04:17 UTC, Takeno-hito requested changes

2023-07-14 04:17 UTC, Takeno-hito commented on docs/chapter2/section1/src/0/main.go
> +			return c.String(http.StatusForbidden, "please login")
401 の方がいいな

2023-07-14 04:17 UTC, Takeno-hito commented on docs/chapter2/section1/0_server_setup.md
> +middleware から次の handler を呼び出すには`next(c)`と書きます。
middleware は複数あることもあるので、次の関数〜くらいで良い

2023-07-14 04:17 UTC, Takeno-hito commented on docs/chapter2/section1/0_server_setup.md
> +まず、この関数は handler ではありません。handler 関数を返す関数です。(middleware と呼ばれています) リクエスト→middleware→handler という順序で処理されます。
ミドルウェアについてちょっと説明がほしいです。

2023-07-14 04:30 UTC, nokhnaton commented on docs/chapter2/section1/1_router-setup.md
> +# プロキシの設定
サーバーでCORSとかの設定するのすっとできないのでとりあえずあと回しにします

2023-07-14 04:31 UTC, nokhnaton commented on docs/chapter2/section1/0_server_setup.md
> +<<<@/chapter2/section1/src/0/main.go{go:line-numbers}
先に全体像見えてた方がわかりやすいと思っているのですが、どうでしょう?

2023-07-14 04:46 UTC, nokhnaton commented on docs/chapter2/section1/0_server_setup.md
> +middleware から次の handler を呼び出すには`next(c)`と書きます。
次の関数だと関数がなんなのかの具体性が抜けちゃって混乱しそうなので、「handler や middleware など」とかの方がいいとは思います

2023-07-14 06:04 UTC, mehm8128 commented on docs/chapter2/section1/0_server_setup.md
> +<<<@/chapter2/section1/src/0/main.go{go:line-numbers}
僕が受けた当時は最初に一気に提示されたのは分かりにくいと感じたので、他の人の意見も聞きたいです
先に全体像を見せたいのであれば全部ではなく、実装する関数とその概要とかだけ先に提示するとかならありかも

2023-07-14 07:32 UTC, sapphi-red commented on docs/chapter2/section1/0_server_setup.md
> +基本的に Password を平文で保存しておくのは危険です！　従って、パスワードを DB に格納するときはハッシュ化を行ってから格納してください。本来はハッシュ化の有効性を高めるためにハッシュソルトというものを使用するべきなのですが、今回は割愛します。興味がある人は調べてみてください。
bcryptはソルトも使ってくれるので文のつながりが誤解を招きそうです

2023-07-14 07:32 UTC, sapphi-red commented on docs/chapter2/section1/1_router-setup.md
> +SPA を作る際には、`PATH`に応じたページを描画する Router のような補助ライブラリが使用すると便利です。
PATHを大文字にすると環境変数のPATHと紛らわしい気がします

2023-07-14 07:32 UTC, sapphi-red commented on docs/chapter2/section1/2_axios.md
> +
そろそろaxiosじゃなくてfetchそのままとか[ky](https://github.com/sindresorhus/ky)とかにしちゃってよさそうだと思います

2023-07-14 07:32 UTC, sapphi-red commented on docs/chapter2/section1/2_axios.md
> +上のように何らかのエンドポイントを叩いた結果、403 が返ってきたらリダイレクトするようにしてもいいですが、今回は traQ やその他 traP の Vue での書き方に習って、`whoami`というエンドポイントを使ってログインされているかの確認をします。
> Vue での書き方

ここでは別に「Vue」関係ないと思うので、フロントエンドなりクライアントのが正しそうです

2023-07-14 07:32 UTC, sapphi-red commented on docs/chapter2/section1/src/0/main.go
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token"))
ここのsecret-token、隠すべきものなので、環境変数にしたほうがよさそうです

2023-07-14 07:32 UTC, sapphi-red commented on docs/chapter2/section1/src/0/main.go
> +	db.Get(&city, "SELECT * FROM city WHERE Name=?", cityName)
ここ、エラーハンドリングが抜けている気がします

あと忘れちゃったけど、`db.Get`って見つからなかったとき、`sql.ErrNoRows`が返ってきたような気もする

2023-07-14 07:32 UTC, sapphi-red commented on docs/chapter2/section1/src/0/main.go
> +	id, _ := result.LastInsertId()
ここもちゃんとエラーハンドリングしたほうがよさそうだと思います

2023-07-15 01:58 UTC, ikura-hamu commented on docs/chapter2/section1/0_server_setup.md
> +### main.go の設定
「{{ファイル名}}の設定」っていう表現に違和感があるので、「{{ファイル名}}の編集」とか「作成」とかがいい気がする。お好みでいいと思うけど。下のhandler.goも

2023-07-15 01:58 UTC, ikura-hamu commented on docs/chapter2/section1/0_server_setup.md
> +<<<@/chapter2/section1/src/0/main_handler.go#var{go:line-numbers}
第一部から基本的にコードの行数は表示しないできたから、それに合わせてほしい。

2023-07-15 02:05 UTC, ikura-hamu reviewed
全体的に長い気がするから分割したいけど、区切りが分かんない。

2023-07-15 02:05 UTC, ikura-hamu commented on docs/chapter2/section1/src/0/final/code.go
> +	req := LoginRequestBody{}
ここも`var req LoginRequestBody`

2023-07-15 02:05 UTC, ikura-hamu commented on docs/chapter2/section1/src/0/final/code.go
> +			return c.String(http.StatusUnauthorized, "please login")
`echo.NewHTTPError`とどっちかに統一した方がいいと思う。

2023-07-15 02:44 UTC, ikura-hamu reviewed
細かいけど

2023-07-15 02:44 UTC, ikura-hamu commented on docs/chapter2/section1/src/0/final/code.go
> +	req := LoginRequestBody{}
`var req LoginRequestBody`

2023-07-15 02:44 UTC, ikura-hamu commented on docs/chapter2/section1/src/0/final/code.go
> +	req := LoginRequestBody{}
`var req LoginRequestBody`

2023-07-15 02:44 UTC, ikura-hamu commented on docs/chapter2/section1/src/0/final/code.go
> +	city := City{}
`var city City`

2023-07-15 02:50 UTC, ikura-hamu reviewed
typo

2023-07-15 02:50 UTC, ikura-hamu commented on docs/chapter2/section1/2_session.md
> +従って、これらのエラーの内容に応じて、 500 (Internal Server Erorr) 401 (UnAuthorized) を返却するか、処理を続行するかを選択していきます。
Er**or**rになってる

2023-07-15 02:50 UTC, ikura-hamu commented on docs/chapter2/section1/2_session.md
> +最後に、middlerware を設定しましょう。
みどらーわれーになってる

2023-07-15 02:52 UTC, ikura-hamu commented on docs/chapter2/section1/2_session.md
> +従って、これらのエラーの内容に応じて、 500 (Internal Server Erorr) 401 (UnAuthorized) を返却するか、処理を続行するかを選択していきます。
Unauthorizedはa小文字な気がする

2023-07-15 03:10 UTC, ikura-hamu approved these changes
いけそう

2023-07-15 03:17 UTC, Takeno-hito approved these changes

2023-07-15 03:17 UTC, mehm8128 approved these changes

2023-07-15 03:18 UTC, merged

2023-07-15 03:48 UTC, mehm8128 reviewed
細かいところ色々書きました(書いてから気づいたけど、PRとして出した方がよかったかも)

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/1_account.md
> +今回の目標は、 `/cities/` で始まる api (getCityInfoHandler, postCityHandler) 2 つに対して、
```suggestion
今回の目標は、 `/cities/` で始まる api 2 つ(`getCityInfoHandler`, `postCityHandler`) に対して、
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/1_account.md
> +ソルトはさっき説明しました。
```suggestion
ソルトは上で説明しました。
```
もしくは
```suggestion
ソルトは先ほど説明しました。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/1_account.md
> +Username,HashedPassword を持つ User レコードをデータベースに追加しましょう。
```sugesstion
`Username`, `HashedPassword` を持つ User レコードをデータベースに追加しましょう。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/1_account.md
> +このコードは後々の回で使用するので、エンドポイント (`/signup` など) は変更しないでください！
```suggestion
このコードは後々の回で使用するので、エンドポイントのパス (`/signup` など) は変更しないでください！
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/1_account.md
> +ここまでできたら、実行して、PostMan 等を用いて正しく実装できているかデバッグしてみましょう。
```suggestion
ここまでできたら、実行して、Postman 等を用いて正しく実装できているかデバッグしてみましょう。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +セッションとは、今来た人が次来たとき、同じ人であることを確認するための仕組みです。
ここちょっと説明微妙かも？

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +ここで、エラーチェックは `==` を使ってはいけません。 `errors.Is` を使いましょう。
参考資料ほしい

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +ハッシュ化は不可逆な処理なので、ハッシュ化されたものから原文を調べることはできません。確認する際はもらったパスワードをハッシュする事で行います。
```suggestion
ハッシュ化は不可逆な処理なので、ハッシュ化されたものから原文を調べることはできません。確認する際はもらったパスワードをハッシュ化することで行います。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +- 処理中にこれ以外の問題が発生した場合は、返り値はエラー型の何かです。
箇条書きは普通文末に句点つけないらしい(textlintでエラー出ないのかな)

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +- 一致しない場合、 `bcrypt.ErrMismatchedHashAndPassword` が帰ってきます。
```suggestion
一致しない場合、 `bcrypt.ErrMismatchedHashAndPassword` が返ってきます
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +従って、これらのエラーの内容に応じて、 500 (Internal Server Error) 401 (Unauthorized) を返却するか、処理を続行するかを選択していきます。
```suggestion
従って、これらのエラーの内容に応じて、 500 (Internal Server Error)、 401 (Unauthorized) を返却するか、処理を続行するかを選択していきます。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +セッションに登録します。セッションについては今回は深掘りしません。
気になる人はこちら、で参考資料ほしい

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +続いて、userAuthMiddleware を実装します。
```suggestion
続いて、`userAuthMiddleware` を実装します。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +関数が関数を呼び出していて混乱しそうですが、 2 行目から 13 行目が本質で、外側はおまじないと考えて良いです。
行数使って説明するならコードブロックに行番号振った方が分かりやすそう

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +来るリクエストは、Middleware を経由して、 Handler に流れていきます。
```suggestion
送られてくるリクエストは、Middleware を経由して、 Handler に流れていきます。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +このミドルウェアはリクエストを送ったユーザーがログインしているのかをチェックし、
```suggestion
このMiddlewareはリクエストを送ったユーザーがログインしているのかをチェックし、
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +まず、これは Handler ではなく middleware と呼ばれます。
```suggestion
まず、これは Handler ではなく Middleware と呼ばれます。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +最後に、middleware を設定しましょう。
```suggestion
最後に、Middleware を設定しましょう。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/2_session.md
> +セッションからアクセスしているユーザーの`userName`を取得して返しています。
```suggestion
アクセスしているユーザーの`userName`をセッションから取得して返しています。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/3_verify.md
> +`go run main.go`でサーバーを起動した状態で行ってください
```suggestion
全て Postman での検証です。  
`go run main.go`でサーバーを起動した状態で行ってください。
```
改行もできてなさそう

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/3_verify.md
> +![](https://md.trapti.tech/uploads/upload_7b21cf42397801806bab12f5180ce888.png)
ここらへん画像が古くてURLが違う

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/3_verify.md
> +![](https://md.trapti.tech/uploads/upload_59c6c86e127d982f511946d2a183d0a6.png)
ここも画像古い

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/3_verify.md
> +Value に`sessions=(コピーした値);`をセットします(既に自動で入っている場合もあります、その場合は追加しなくて大丈夫です)。
```suggestion
Value に`sessions={コピーした値};`をセットします(既に自動で入っている場合もあります、その場合は追加しなくて大丈夫です)。
```

2023-07-15 03:48 UTC, mehm8128 commented on docs/chapter2/section1/4_extra.md
> +TODO リストのサーバーとしての API を考えて作ってみましょう。完成したら実況チャンネルに投稿しましょう。
このTODOってどういう意味でのTODOですか？なんかまだ書く予定ですか？

2023-07-15 03:53 UTC, ikura-hamu commented on docs/chapter2/section1/4_extra.md
> +TODO リストのサーバーとしての API を考えて作ってみましょう。完成したら実況チャンネルに投稿しましょう。
「ToDo リスト」のことだと思います

2023-07-15 03:55 UTC, mehm8128 commented on docs/chapter2/section1/4_extra.md
> +TODO リストのサーバーとしての API を考えて作ってみましょう。完成したら実況チャンネルに投稿しましょう。
あ、なるほど...

2023-07-15 03:56 UTC, mehm8128 commented on docs/chapter2/section1/4_extra.md
> +TODO リストのサーバーとしての API を考えて作ってみましょう。完成したら実況チャンネルに投稿しましょう。
普段ここにスペース空けない派なので気づかなかった

2023-07-15 04:40 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +セッションとは、今来た人が次来たとき、同じ人であることを確認するための仕組みです。
セッションの説明が第5回にはなかったのですが第6回にはあるので、ここの説明消します　僕も困ってたので、、