2章第2回
traPtitech/naro-text pull request #89
Opened 2023-07-16 05:55 UTC by nokhnaton

vue-router, proxy, サーバーとの通信の話。

2023-07-16 06:41 UTC, ikura-hamu commented on docs/chapter2/section2/0_router-setup.md
> +::info
コロンが1個足りない

2023-07-16 06:41 UTC, ikura-hamu commented on docs/chapter2/section2/1_proxy.md
>  `localhost:3000/api/*`へのリクエストを、自分のサーバーの`133.130.109.224/*`へプロキシする設定を書きます。
今回サーバー側はlocalhost:8080で動いてるから、それに合わせて変える必要がある

2023-07-16 06:41 UTC, ikura-hamu commented on docs/chapter2/section2/2_fetch.md
> +:::info
今まで課題は何も囲まずに書いてたので、それに合わせてください

2023-07-16 06:41 UTC, ikura-hamu commented on docs/chapter2/section2/2_fetch.md
>  Chrome のシークレットウィンドウを起動し、先程の`/city/Tokyo`を開いてみます。
Chromeじゃなくて「ブラウザ」がよさそう。それともChromeに限定してたっけ

2023-07-16 06:41 UTC, ikura-hamu commented on docs/chapter2/section2/2_fetch.md
> +上のように何らかのエンドポイントを叩いた結果、403 が返ってきたらリダイレクトするようにしてもいいですが、今回は traQ やその他 traP のアプリケーションでの書き方に習って、`whoami`というエンドポイントを使ってログインされているかの確認をします。
whoamiは前回実装してある。traQも同じ働きをするエンドポイントはあるけど、別にwhoamiっていう名前のエンドポイントは無いから、言い回しを変えた方がよさそう。

2023-07-16 06:41 UTC, ikura-hamu commented on docs/chapter2/section2/2_fetch.md
> +:::tip
tipではなさそう。何も囲まなくていいかも。([READEME](https://github.com/traPtitech/naro-text/blob/main/README.md))

2023-07-16 06:48 UTC, ikura-hamu commented
他は、
- `<details>`を使ってるところは、`:::details`に書き換えられる。
- 見出しの大きさ（`#`の数）を他のページと統一してほしい。
- 課題とかは:::を使う必要はなく、READMEとか他のページを見ていい感じに使ってほしい。

らへんを修正してほしいです。（今回のPRでの変更じゃなかったからreviewで入れられなかった）お願いします。

フロントのお作法とかはわからないので、詳しい人お願いします。

2023-07-16 06:51 UTC, mehm8128 requested changes
いくらはむくんと被ってるところもあるけど簡単に見ました
動作確認はしてません

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +[第二回](https://md.trap.jp/grYPeJzbSxWDfz5qHZfXYQ#%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E4%BD%9C%E6%88%90)と同じように https://github.com/hijiki51/naro-template のテンプレートリポジトリからリポジトリを作成します。
どっちもURL変えておいてください

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +:::tip
tipじゃないかも

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +今日は下の[最重要課題](#最重要課題)を一番やってほしいです。
今日→今回
下→下じゃなくて別のページ
最重要課題→リンク飛べない

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +## 1. ライブラリのインストール
確かVueのプロジェクト作るときにオプションでインストールできるようになってたからそれでテンプレートリポジトリ修正しておいてもいいかも
そうしたら`router.ts`も`router/index.ts`として作られた気がするし

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +:::
表示バグってる＆改行反映されてなさそう

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +`router.js`に定義した Route の配列は先頭からマッチします。
`router.ts`

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +`<router-view>`というコンポーネントは自身のパスに応じて描画するコンポーネントを変えるものです。その設定を`router.ts`で行っています。
表記揃えるなら
>自身の`path`

になりそう？

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/1_proxy.md
結局サーバーの設定じゃなくてプロキシ使う方針ということでOKですか？

その他
- 改行反映されてないところがある
- IPアドレス&ポート番号古いまま
- route.js→router.ts

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/1_proxy.md
>  # プロジェクト構成
これここじゃなくて前のページで書いた方がよさそう

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
他のページも(もしかしたら前の回のページもかも)なんですけど、基本的に`h1`に当たる見出しは1つのページに1つにした方がいいと思います

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
>  `route.ts`に`PingPage`を追加するのも忘れず行いましょう。
`router.ts`

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
前に一旦マージしたところインラインでコメントできなかったのでここで書きます
- 「サーバーとの通信処理は長時間かかる事があり」みたいなのって「事」を漢字で書くの不自然な気がします
- `onMounted`の参考資料ほしいかも
- fetchとかの参考資料改行できてない
- 「昨日作った都市の情報を返す API を表示するページを作成します。」→前回作った～

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
> +上のように何らかのエンドポイントを叩いた結果、403 が返ってきたらリダイレクトするようにしてもいいですが、今回は traQ やその他 traP のアプリケーションでの書き方に習って、`whoami`というエンドポイントを使ってログインされているかの確認をします。
401？

2023-07-16 06:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
> +:::tip
tipじゃない
囲わなくてよさそう

2023-07-16 06:52 UTC, mehm8128 commented
あ、もっと書いたのに保存してなくて消えちゃった

2023-07-16 06:59 UTC, mehm8128 reviewed
なんかもうちょっとあった気がするけど消えちゃって忘れちゃった
思い出したらまた書きます

2023-07-16 06:59 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
- 「res.json()としている部分では、サーバーからのレスポンスを json として解釈しています。」→jsonとして解釈してJSのオブジェクトに変換しています、くらいほしいかも
- router.js→router.ts(たくさんあります)
-  ここでは、Vue Router の meta という機能を使って→`meta`
- サーバーサイドの変更をします。→してなさそう
- 好みかもだけど`username`とか型推論してくれるからジェネリクスでわざわざstring指定しなくてもよさそう

2023-07-16 07:02 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
思い出した
- クライアントの見本：https://github.com/itt828/naro-client-2022-v2→見本作成ししてURL変えといてください

2023-07-16 08:11 UTC, nokhnaton commented on docs/chapter2/section2/0_router-setup.md
> +## 1. ライブラリのインストール
初めてなので手動で作ったほうがわかりやすいと思ってるので、このままで行きます

2023-07-16 08:16 UTC, nokhnaton commented on docs/chapter2/section2/1_proxy.md
infoでサーバーの設定で回避する方法を書くことにします

2023-07-16 12:21 UTC, ikura-hamu reviewed
ちょっとだけ

2023-07-16 12:21 UTC, ikura-hamu commented on docs/chapter2/section2/2_fetch.md
>  <details>
:::details

2023-07-16 12:21 UTC, ikura-hamu commented on docs/chapter2/section2/2_fetch.md
>  :::info
ここは囲まなくてよさそう

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +│   ├── main.js
main.ts

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +└── vite.config.js
vite.config.ts

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +## プロジェクト構成
プロジェクト構成、第1部で同じようなの書いてあったからいらなさそう

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +参考: [Vue Router](https://next.router.vuejs.org/)
ここらへんは上でinfoとかで書いてあったし、上の初めて出てきた箇所でそれぞれ説明すればよさそう

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +ページを表します。
これはいらなさそう

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/1_proxy.md
> +## プロキシとは
infoとかの中で見出し使うのややな気がします、変な表示になっちゃってるし
![image](https://github.com/traPtitech/naro-text/assets/83744975/2b282435-20a8-4ccd-a5c0-48cea0b84ff4)

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/1_proxy.md
> +## プロキシとは
参考資料改行反映されてないです

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/1_proxy.md
>プロジェクトルートの`vite.config.js`というファイルの内容を、以下の内容に変更します。

vite.config.ts

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/1_proxy.md
> +この設定をした場合、以降の`/api/*`にアクセスしている部分を`http://localhost:8080/*`にアクセスさせるようてください。
>させるようてください。

させるようにしてください？

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
>  また、関数実行の前に`await`とついているのはこの関数の処理が終わるまで次の処理を待つということを表しています。これをやらないと処理が終わる前に次の処理に進んでしまう事があります。
次の処理に進んでしまう事があります。
も
次の処理に進んでしまうことがあります。

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
>`route.ts`に`PingPage`を追加するのも忘れず行いましょう。

router.ts

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
> +#### src/router.ts
ここに見出しあるのミス？

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
> +#### これでサーバー・クライアント両方でAPIを利用する方法がわかりました。
見出しにしなくてよさそう

2023-07-16 14:51 UTC, mehm8128 commented on docs/chapter2/section2/2_fetch.md
> +クライアントの見本：https://github.com/traPtitech/naro-template-frontend/tree/city
ソースコードでファイル名が`CItyPage.vue`になってる(iが大文字)

2023-07-17 03:08 UTC, ikura-hamu reviewed
ぎりぎりになって申し訳ない。頼んだ！時間無ければやります。

2023-07-17 03:08 UTC, ikura-hamu commented on docs/chapter2/section2/1_proxy.md
> +ログインや街の情報の取得などは、リモートのサーバーに送信したいわけですが、`localhost`から配信されているクライアントから`133.130.109.224`に対してリクエストを送ろうとするとブラウザのセキュリティ機構に制限されたりと面倒なことがあります。
IPアドレスがそのままになっている。

2023-07-17 03:08 UTC, ikura-hamu commented on docs/chapter2/section2/2_fetch.md
> +:::details
`:::details 解答`　ってするとsummary使わなくてもいい感じになる

2023-07-17 03:08 UTC, ikura-hamu commented on docs/chapter2/section2/2_fetch.md
>  Chrome Devtool から見てみるとログインしていないため、ダメだということがわかりました。
上で「ブラウザ」って言ってるからここもChromeとは言わないほうがよさそう

2023-07-17 03:08 UTC, ikura-hamu reviewed
ぎりぎりになって申し訳ない。頼んだ！時間無ければやります。

2023-07-17 03:14 UTC, ikura-hamu reviewed
1こ

2023-07-17 03:14 UTC, ikura-hamu commented on docs/chapter2/section2/1_proxy.md
> +これらを避けるために、`localhost:8080/*`へのリクエストを`localhost:5173/api/*`として手元のサーバーに送信し、手元のサーバーがブラウザの代わりにリモートのサーバーにリクエストを送信します。手元のサーバーは、リモートのサーバーからのレスポンスを透過的にブラウザに返却するので、ブラウザからはあたかも`localhost:3000/api/*`がレスポンスを返して
3000が残っちゃってる

2023-07-17 03:15 UTC, mehm8128 commented on docs/chapter2/section2/0_router-setup.md
> +参考: [`router-view` | Vue Router](https://next.router.vuejs.org/guide/#router-view)
改行反映されてないです
目ですぐ確認できるものはちゃんと確認してほしいです

2023-07-17 03:15 UTC, mehm8128 commented on docs/chapter2/section2/1_proxy.md
> +サーバーを書き換えることにより CORS を回避できます。クライアントとサーバーをそれぞれ別のオリジンで配信する場合はこちらの方法を用いた方が良いです。
>クライアントとサーバーをそれぞれ別のオリジンで配信する場合はこちらの方法を用いた方が良いです。

これ、今回もポート番号違うので別のオリジンじゃないですか？(同じオリジンならCORSエラー出ないはず)

2023-07-17 03:21 UTC, nokhnaton commented on docs/chapter2/section2/1_proxy.md
> +サーバーを書き換えることにより CORS を回避できます。クライアントとサーバーをそれぞれ別のオリジンで配信する場合はこちらの方法を用いた方が良いです。
これ実際にサーバーに乗っけてポートを開いて公開することを「配信」って言ってます。「公開」とかに変えた方がわかりやすいですかね?

2023-07-17 03:25 UTC, mehm8128 commented on docs/chapter2/section2/1_proxy.md
> +サーバーを書き換えることにより CORS を回避できます。クライアントとサーバーをそれぞれ別のオリジンで配信する場合はこちらの方法を用いた方が良いです。
あーなるほど
まあどっちでもいい気がするのでこのままでもOKです

2023-07-17 03:31 UTC, mehm8128 approved these changes
よさそうな気がします

2023-07-17 03:42 UTC, merged