間違えていたコード部分や、salt、レインボーテーブルの修正
traPtitech/naro-text pull request #90
Opened 2023-07-16 13:22 UTC by pikachu0310

2023-07-18 01:51 UTC, Takeno-hito commented
resolve: #93

2023-07-18 01:53 UTC, Takeno-hito commented
他にも直さないといけないところが複数あるので、 #93 見ながら直してくれると助かります（別にめんどいならこのまま一旦マージでも良いと思うので、そっちの方が良いなら言ってください。レビューします）

2023-08-06 04:21 UTC, pikachu0310 commented
変更がとても肥大化しているので、現地点で完成している0_setup.mdと1_account.mdをレビューしてほしいです。 @Takeno-hito 

docs/chapter2/section1/0_setup.md
docs/chapter2/section1/1_account.md

2023-08-06 12:12 UTC, ikura-hamu reviewed
たけのひとじゃないけどレビューしました。お願いします。

2023-08-06 12:12 UTC, ikura-hamu commented on docs/chapter2/section1/0_setup.md
>  ファイルを編集したら、`go mod tidy` を実行しましょう。
ここの時点だとhandlerが無くてエラーが出るはずだから、「エラーが出てても無視してください」って書くか、handler.goを先に書いた方がいいと思います。

2023-08-06 12:12 UTC, ikura-hamu commented on docs/chapter2/section1/src/0/first/handler.go
>  	if !city.Name.Valid {
上でerrorを取って、ifは`errors.Is(err, sql.NoRows)`とかの方がよくみる気がする。

2023-08-06 12:12 UTC, ikura-hamu commented on docs/chapter2/section1/src/0/first/handler.go
>  		log.Printf("failed to insert city data: %s\n", err)
下の方は`fmt.Printf()`でやってるから、どっちかに統一するといいと思います。

2023-08-27 06:59 UTC, pikachu0310 commented on docs/chapter2/section1/src/0/first/handler.go
>  	if !city.Name.Valid {
これどちらでも良いと思ったんだけど、どっちの方が良いんだろう？と思ってたんだけど、これって
err != nil で InternalServerError返すべきじゃない？

2023-08-27 07:01 UTC, pikachu0310 commented on docs/chapter2/section1/src/0/first/handler.go
>  	if !city.Name.Valid {
つまりこう
```
	err := h.db.Get(&city, "SELECT * FROM city WHERE Name=?", cityName)
	if errors.Is(err, sql.ErrNoRows) {
		return c.NoContent(http.StatusNotFound)
	} else if err != nil {
		fmt.Printf("failed to get city data: %s\n", err)
		return c.NoContent(http.StatusInternalServerError)
	}
```
でどうですか？

2023-08-27 07:18 UTC, pikachu0310 commented on docs/chapter2/section1/src/0/first/handler.go
>  		log.Printf("failed to insert city data: %s\n", err)
fmtとlogの使い分けってひょっとしてあるのかな？今回はlog.Printlnとかの方が適切そうな気がする

2023-08-27 08:10 UTC, hijiki51 commented on docs/chapter2/section1/src/0/first/handler.go
>  	if !city.Name.Valid {
```go
if err != nil {
    if errors.Is(err, sql.ErrNoRows) {
        //処理
        // (returnしたりしなかったり)
    }
    // 処理
    return
}
```

みたいな形が多き気がする

2023-08-27 08:27 UTC, pikachu0310 commented
去年以前の資料で、Bindのエラーハンドリングがされていなくて、そのままで良いのかなぁとなってます。何か理由があるのでしょうか？下は具体的な例です。

```
func (h *Handler) LoginHandler(c echo.Context) error {
	var req LoginRequestBody
	c.Bind(&req)
	if req.Password == "" || req.Username == "" {
		return c.String(http.StatusBadRequest, "Username or Password is empty")
	}
```
を
```
func (h *Handler) LoginHandler(c echo.Context) error {
	var req LoginRequestBody
	err := c.Bind(&req)
	if err != nil {
		return c.String(http.StatusBadRequest, "Invalid request body")
	}
	if req.Password == "" || req.Username == "" {
		return c.String(http.StatusBadRequest, "Username or Password is empty")
	}
```
にした方が良いのかなと思っているのですが、どうなのでしょうか

2023-08-27 08:28 UTC, hijiki51 commented
たぶんそんなに深い理由はないのでハンドリングしちゃってください

2023-08-27 08:52 UTC, pikachu0310 commented on docs/chapter2/section1/src/0/first/handler.go
>  	if !city.Name.Valid {
確かに、となりました。これでいきます:pray:

2023-08-28 23:52 UTC, Takeno-hito requested changes
レビュー仕切るのに時間がかかりそうなので、少しずつレビューします :pray: memo: 0, 1 節のレビューです！

P.S; https://zenn.dev/hacobell_dev/articles/code-review-comment-prefix に沿ってレビューに prefix を付けてみたので参考にしてください！このレビューが分かりづらいとかあったら遠慮なく言ってください。

2023-08-28 23:52 UTC, Takeno-hito commented on docs/chapter2/section1/1_account.md
> +ここまでできたら、実行して、Postman 等を用いて正しく実装できているかデバッグしてみましょう。以下は例です。
NITS; 「以下は例です」→「正しく実装できていれば、例えば以下のようにデバッグできます」

2023-09-01 04:31 UTC, pikachu0310 commented
これはレビューがまだ途中だと思うのですが、レビュー部分を直したらもうpushしちゃって大丈夫ですか？

2023-09-01 04:36 UTC, pikachu0310 commented on docs/chapter2/section1/0_setup.md
> +3. `.env`ファイルの環境変数を、プログラムで読むようにした。
IMO; 僕の意見では、第一部で扱ってるコードの量は少ないですし、第一部では本当の入門でありとっつきやすさも重視したいなと思っています。なので第一部はこのままで、コードの量が増えてより煩雑になる第二部にて、パッケージ分けの説明を添えた上でパッケージ分けをすればよさそうというのが僕の意見です。

2023-09-01 04:43 UTC, pikachu0310 commented on docs/chapter2/section1/0_setup.md
> +3. `.env`ファイルの環境変数を、プログラムで読むようにした。
`.env`の中身に問題があるという意味ですか？

2. `.env` ファイルを作成し、以下のように編集しましょう。
```sh
export DB_USERNAME="root"
export DB_PASSWORD="password"
export DB_HOSTNAME="localhost"
export DB_PORT="3306"
export DB_DATABASE="world"
```

と書いてあるし、動くので問題ないと思うのですが...

2023-09-01 05:25 UTC, pikachu0310 commented on docs/chapter2/section1/1_account.md
> +    if req.Password == "" || req.Username == "" { // [!code ++]
アリですが、分かりやすさを重視するために今回はこのままでいきたいと思います。

2023-09-01 05:26 UTC, pikachu0310 commented on docs/chapter2/section1/1_account.md
> +func (h *Handler) SignUpHandler(c echo.Context) error { // [!code ++]
今回全体的に記述するコードの量が多いため、なるべく分かりやすくした方が良いと思いこのような形式にしました。僕は今のままで良いと思っているのですが、他の人の意見を聞きたいかもです。

2023-09-01 13:01 UTC, Takeno-hito commented
> これはレビューがまだ途中だと思うのですが、レビュー部分を直したらもうpushしちゃって大丈夫ですか？

普通にコミットしたらそのまま push してもらって大丈夫です～

2023-09-01 13:10 UTC, Takeno-hito commented on docs/chapter2/section1/0_setup.md
> +3. `.env`ファイルの環境変数を、プログラムで読むようにした。
これでも動くの知らなかった、それはごめんなさい。
ただ、`.env` ファイルの中身は `DB_USERNAME="root"` とかなってる方が普通だと思うから、テキストでもそれで教えたいなぁ、という気持ちがあります。これは他の IMO とかついてるレビューにも通じる話だけど

2023-09-01 13:34 UTC, Takeno-hito requested changes
遅れてごめんなさい、追加です～　あとは修正してもらったあとに、最後に一回通しで眺めたら ok かなと考えてます！

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +最初では、セッションの情報を記憶するための場所をデータベース上に設定しています。
NITS; 「最初では…しています」→「最初に…設定します」

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +続いて、`loginHandler` を `handler.go` に実装していきましょう。
MUST; ここも先頭小文字になってます

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +    HashedPass string `json:"-"  db:"HashedPass"` // [!code ++]
FYI; 普段の開発だと、テーブルのカラムはハッシュ化されてる前提で `password` になってると思います。まぁ変えなくても？

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token")) // [!code ++]
FYI; ここの `secret-token` がペッパーに相当するものだった、みたいな話をみどりさんがしていた気がする。本当は環境変数にしたいけど、まぁ面倒っちゃ面倒

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +    var req LoginRequestBody // [!code ++]
MUST; ここもソフトタブ・ハードタブの混入があります

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/1_account.md
> +:::info 参考: ソルトについて
IMO; tips でもいいかも

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +:::info
NITS; tips にしても良い気がしなくもないです（info のままでも別に良いような気もします。ちょっと気になったくらい）

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +:::details ここまでの全体像
FYI; code-groups が使えるので使うとちょっとかっこいいかも https://vitepress.dev/guide/markdown#code-groups

IMO; 完成形くらいはソースコードとして保存してそれを引っ張ってきて良い気がします

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +	e.POST("/login", h.LoginHandler)
ここもソフトタブとハードタブが混ざってる

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +## getMeHandler の実装
これも大文字小文字問題があります

2023-09-01 13:34 UTC, Takeno-hito commented on docs/chapter2/section1/3_verify.md
> +![](images/3/postman2-signup.png)
NITS; 別にファイル名に番号振らなくてもいいんじゃない？と思ったけど振った方がいい面もあるので、別に良いやと思ったら変えなくても全然okです

2023-09-02 00:28 UTC, pikachu0310 commented on docs/chapter2/section1/0_setup.md
> +3. `.env`ファイルの環境変数を、プログラムで読むようにした。
あ、確かに`source`しないときは`export`付けないのが普通ですね、直します(目が節穴でした)

2023-09-02 00:29 UTC, pikachu0310 commented on docs/chapter2/section1/0_setup.md
> +3. `.env`ファイルの環境変数を、プログラムで読むようにした。
これパッケージ分けの話ではなかったんですね、godotenvの導入の話なら良いと思います。他issueで立てましょう。

2023-09-02 00:37 UTC, pikachu0310 commented on docs/chapter2/section1/1_account.md
> +:::info 参考: ソルトについて
tip: 注釈（Git/CLI の操作法など）
info: 発展的な内容、コラム

IMO; ソルトは発展的な内容、コラムに相当すると思っているので、infoのままで良いと思いました

2023-09-02 00:40 UTC, pikachu0310 commented on docs/chapter2/section1/2_session.md
> +:::details ここまでの全体像
code-groupsアリだと思ってたのですが、初見でこの形式を見る人全員がこの形式のクリックで切り替えが可能なことに気づけるかって言われたらちょっと怪しいな～っていう感想です。クリックで変更できますという注釈を入れた上でcode-groupsにしようかな？

完成形をソースコードとして保存は賛成です。

2023-09-02 00:43 UTC, pikachu0310 commented on docs/chapter2/section1/2_session.md
> +    HashedPass string `json:"-"  db:"HashedPass"` // [!code ++]
確かにそうですね。今回は分かりやすく(データーベースを見た時に)HashedPassで良いかなぁと思いますが、普通はHashedPassでやるものなのだと勘違いさせる原因にもなりそうです。これはtipで明記しておいた方が良いかな？

2023-09-02 00:57 UTC, pikachu0310 commented on docs/chapter2/section1/2_session.md
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token")) // [!code ++]
内部実装を見に行ったのですが、ハッシュ値を操作するようなものではなく、暗号化/復号化の際に使われる秘密鍵のような役割をしているようです。
本当は環境変数にしたいには賛成ですが、今回はこのままでいきます。(環境変数を複雑にして分かりにくさを増幅させたくない)

2023-09-02 01:06 UTC, pikachu0310 commented on docs/chapter2/section1/2_session.md
> +:::details ここまでの全体像
![image](https://github.com/traPtitech/naro-text/assets/17543997/1e1cb457-21de-40e5-838a-37bdd376d3b7)

案外分かりやすかったのでこれで行きます:ok:

2023-09-02 01:16 UTC, pikachu0310 commented on docs/chapter2/section1/2_session.md
> +    HashedPass string `json:"-"  db:"HashedPass"` // [!code ++]
:::tip
パスワードをデーターベースに保存する際はハッシュ化するのが当たり前なので、ハッシュ化されたパスワードのためのデータベーステーブルのカラム名には`password`が使われるのが一般的です。  
今回は混乱しないように`HashedPass`という名前でカラムを作成しています。
:::

を追記しました

2023-09-02 02:20 UTC, pikachu0310 commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
:::tip
パッケージとは、関連する複数のファイルをまとめる単位のことです。  
ディレクトリとパッケージは一対一に対応しています。原則的に、ディレクトリ名とパッケージ名は同じにします。    
パッケージによって、機能を分離でき、変数や関数の公開範囲を最低限にできる等沢山の恩恵が得られます。  
パッケージの外部に公開する変数や関数などのシンボルは、先頭を大文字にする必要があります。  
逆に言えば、先頭が大文字でないシンボルは、パッケージの外部からはアクセスできません。  
詳しくは以下を参照してください。
[A Tour of Go - Packages](https://go.dev/tour/basics/1)  
[Effective Go - package-names](https://golang.org/doc/effective_go#package-names)
:::

でどうでしょうか？

2023-09-02 02:20 UTC, pikachu0310 commented on docs/chapter2/section1/src/0/first/handler.go
>  		log.Printf("failed to insert city data: %s\n", err)
全てlogで統一しました。これは第一部の方でも修正する必要があると思います。

2023-09-02 02:25 UTC, pikachu0310 commented
最後の一回通しはまだですが、全てのレビューの反映が終わりました。再レビューを軽くお願いします。:pray:

2023-09-02 02:30 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +それでは、`go run main.go` で実行してみましょう。
一応注：main packageをファイル分割した場合、`go run main1.go main2.go`か`go run .`ですべて読み込む必要がある

2023-09-02 02:36 UTC, hijiki51 requested changes

2023-09-02 02:36 UTC, hijiki51 commented on docs/chapter2/section1/1_account.md
> +	h := handler.NewHandler(db)  // [!code hl]
多分ここは省略しないほうがいい、DIみたいなことするの初めてなのでどこに書けばいいかわからなくなると思う

2023-09-02 02:36 UTC, hijiki51 commented on docs/chapter2/section1/1_account.md
> +	h := handler.NewHandler(db)  // [!code hl]
もしくは新しく各部分の前後数行を出して、ハイライトするか

2023-09-02 02:36 UTC, hijiki51 commented on docs/chapter2/section1/1_account.md
> +func (h *Handler) SignUpHandler(c echo.Context) error { // [!code ++]
コードの中に部分的に追加するならハイライトしたほうがいいけど、ここみたいにコードすべてを記入するならなくてもいいかなとは思います

2023-09-02 02:36 UTC, hijiki51 commented on docs/chapter2/section1/1_account.md
> +参考: <https://en.wikipedia.org/wiki/Salt_(cryptography)>
今回は初心者向けなのでできれば日本語の情報のほうがいいです

2023-09-02 05:35 UTC, Takeno-hito commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
大方 ok だけどちょっと固いような気もします　文章僕が少しいじった方がいいですか？

2023-09-02 05:37 UTC, hijiki51 commented on docs/chapter2/section1/2_session.md
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token")) // [!code ++]
これ一言書いておいたほうがいいです（じつはハッカソンとかでそのままにしているの見かけた）

2023-09-02 05:38 UTC, hijiki51 commented on docs/chapter2/section1/2_session.md
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token")) // [!code ++]
コメントでいいので

2023-09-02 05:41 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
これ普通にtipにする情報じゃないので本文に書いてほしいです。

ちなみにプログラミング講習会では変数のスコープ、public , privateってどのぐらいまでやりました？

2023-09-02 05:44 UTC, Takeno-hito commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
一応やってはいますがかなり軽くしか触っていないので、軽く復習するくらいの説明が欲しいです！

2023-09-02 05:45 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
軽くがどのぐらいかわからないですが、public, private関数といって伝わらないのであれば新しくページはやしてがっつり書くのが必要だと思います

2023-09-02 05:48 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
今資料見たけど一番最後に扱ってるだけっぽいのでちゃんと書いたほうがよさそう

2023-09-02 05:49 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
~~publicで検索かけただけなので見落としてる説はある~~

2023-09-02 05:50 UTC, Takeno-hito commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
流石に private public の話をがっつりやるとちょっと重くなっちゃうので、別 pr にするかプログラミング基礎講習のテキストを今から書き換えるかかなぁとちょっと思います

2023-09-02 05:55 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
そうね、別PRでいいと思います

2023-09-02 05:55 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +### handler.go の作成
issueだけ立てておいてください

2023-10-05 05:27 UTC, pikachu0310 commented on docs/chapter2/section1/0_setup.md
> +それでは、`go run main.go` で実行してみましょう。
説明を追加しました: https://github.com/traPtitech/naro-text/pull/90/commits/c15fb6aab07f391ab6a69b9355c80873734f73e0

2023-10-05 05:28 UTC, pikachu0310 commented on docs/chapter2/section1/1_account.md
> +	h := handler.NewHandler(db)  // [!code hl]
func main を全部書いて、該当箇所をハイライトにしました https://github.com/traPtitech/naro-text/pull/90/commits/c321cee6c1bef91786ff7b321ac684af4fdf38fb

2023-10-05 05:28 UTC, pikachu0310 commented on docs/chapter2/section1/1_account.md
> +参考: <https://en.wikipedia.org/wiki/Salt_(cryptography)>
https://github.com/traPtitech/naro-text/pull/90/commits/278d4f671fa834e06c57f9a1c0115c0eaf542bbc

2023-10-05 05:34 UTC, pikachu0310 commented on docs/chapter2/section1/2_session.md
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token")) // [!code ++]
かんたんにかきました。 https://github.com/traPtitech/naro-text/pull/90/commits/9067e38bc1490da61ca1f28063709b42161d6bfd

2023-10-05 05:35 UTC, pikachu0310 commented on docs/chapter2/section1/1_account.md
> +func (h *Handler) SignUpHandler(c echo.Context) error { // [!code ++]
この章では追加する行はすべて緑にしてあるので、混乱を防ぐためにも今回は全部緑としたいです。

2023-10-05 05:39 UTC, pikachu0310 commented on docs/chapter2/section1/src/0/first/handler.go
>  		log.Printf("failed to insert city data: %s\n", err)
https://github.com/traPtitech/naro-text/issues/116

2023-10-10 05:46 UTC, pikachu0310 commented
レビューはすべて修正してあるので、新たに修正点が無ければ、いつでもマージしてよいと思います。

2023-10-10 05:58 UTC, Takeno-hito approved these changes
LGTM 大規模修正お疲れ様でした！
1点だけ確認してください。

2023-10-10 05:58 UTC, Takeno-hito commented on docs/chapter2/section1/0_setup.md
> +:::warning
NITS: 一応この説明は不要にはなったのでなくてもいいかも？ TIPS にしてもいいかもしれない

2023-10-10 05:58 UTC, Takeno-hito commented on docs/chapter2/section1/1_account.md
> +    h := handler.NewHandler(db)  // [!code hl]
なんか背景真っ白になってる…… が、やるなら別 issue ですね
<img width="782" alt="image" src="https://github.com/traPtitech/naro-text/assets/18237819/8d7e202b-65f9-4222-9808-4f2870163623">

2023-10-12 03:07 UTC, pikachu0310 commented on docs/chapter2/section1/0_setup.md
> +:::warning
tipにした

2023-10-12 03:07 UTC, pikachu0310 commented
レビューはすべて修正してあるので、新たに修正点が無ければ、いつでもマージしてよいと思います。2

2023-10-12 04:10 UTC, hijiki51 requested changes

2023-10-12 04:10 UTC, hijiki51 commented on docs/chapter2/section1/1_account.md
> +	Username string `json:"username,omitempty" form:"username"` // [!code ++]
formって使ってるんだっけ？

2023-10-12 04:10 UTC, hijiki51 commented on docs/chapter2/section1/2_session.md
> +ここで、エラーチェックは `==` を使ってはいけません。 `errors.Is` を使いましょう。
別に使ってはいけないわけではないのでん？となった（曖昧回避目的ならOK）

2023-10-12 04:10 UTC, hijiki51 commented on docs/chapter2/section1/src/final/main.go
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token"))
このsecret-tokenどうしようね（よくない）

2023-10-14 02:09 UTC, pikachu0310 commented on docs/chapter2/section1/2_session.md
> +ここで、エラーチェックは `==` を使ってはいけません。 `errors.Is` を使いましょう。
ここで、エラーチェックは `==` を使うのは良くないです。基本的には、 `errors.Is` を使いましょう。 

にしますか？理由もあった方が良いかな

2023-10-14 02:11 UTC, pikachu0310 commented on docs/chapter2/section1/src/final/main.go
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token"))
:::tip "secret-token"は、暗号化/復号化の際に使われる秘密鍵です。
実際に運用するときはこの"secret-token"を独自の値にしてください。環境変数などで管理するのが良いでしょう。 :::

っていう注がありますが、それでもダメですか？

2023-10-15 01:53 UTC, Takeno-hito commented on docs/chapter2/section1/src/final/main.go
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token"))
環境変数にした方が実際はいいという話はたしかにそうで、ただ今回は環境変数をこれ以上増やすと混乱しかねないという話になって secret-token となっていた気がします。変えれるなら変えたい派ですが、2人の判断に任せようかなと思っています

2023-10-15 02:03 UTC, Takeno-hito commented on docs/chapter2/section1/2_session.md
> +ここで、エラーチェックは `==` を使ってはいけません。 `errors.Is` を使いましょう。
ここで、エラーチェックは基本的に `errors.Is` を使いましょう。 でいいかなぁ… Is を使った方が良い理由の話は wrap の話をしないといけなくなって面倒なので

2023-10-15 02:04 UTC, Takeno-hito commented on docs/chapter2/section1/1_account.md
> +    h := handler.NewHandler(db)  // [!code hl]
#120 で対応して頂いています

2023-10-15 02:08 UTC, Takeno-hito commented on docs/chapter2/section1/0_setup.md
> +このまま演習を始めてしまうとファイルが長くなりすぎてしまうので、ファイルを別のパッケージとして分割します。
うーん、Basic やっても頭に入らないと思います（あれは Go 言語初学者向けのテキストであってプログラミング初心者向けの説明じゃないので）  なのでそのあたりの説明は重複があっても書いた方がいいと僕も思います

2023-10-15 02:14 UTC, hijiki51 commented on docs/chapter2/section1/src/final/main.go
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token"))
あ～書いてあるなら大丈夫です。

2023-10-15 02:14 UTC, hijiki51 commented on docs/chapter2/section1/src/final/main.go
> +	store, err := mysqlstore.NewMySQLStoreFromConnection(db.DB, "sessions", "/", 60*60*24*14, []byte("secret-token"))
見落としてました

2023-10-15 02:15 UTC, hijiki51 commented on docs/chapter2/section1/2_session.md
> +ここで、エラーチェックは `==` を使ってはいけません。 `errors.Is` を使いましょう。
それぐらいの温度感でいいと思います

2023-10-15 02:16 UTC, hijiki51 commented on docs/chapter2/section1/2_session.md
> +ここで、エラーチェックは `==` を使ってはいけません。 `errors.Is` を使いましょう。
まあ確かにWrapの話するのめんどいし非本質だなとなったのでこのままでもOKです

2023-11-02 06:50 UTC, pikachu0310 commented on docs/chapter2/section1/0_setup.md
> +このまま演習を始めてしまうとファイルが長くなりすぎてしまうので、ファイルを別のパッケージとして分割します。
プログラミング初心者の人はそもそも対象外では？(プ基礎やるんだし)  
Tour of Go のリンクも貼ってるし僕はいらないと思います。

2023-11-02 07:00 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +このまま演習を始めてしまうとファイルが長くなりすぎてしまうので、ファイルを別のパッケージとして分割します。
あ、僕が言っているのは、packageの説明をするって話じゃなくて、この文章からだと、既存のコードを別パッケージに移動するってことが伝わらないよねって話でした（ディレクトリを移動するのは伝わるけど、それがhandler packageに移動することは伝わらない）

2023-11-02 07:03 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +このまま演習を始めてしまうとファイルが長くなりすぎてしまうので、ファイルを別のパッケージとして分割します。
tour of goも観てきたけど、たぶんディレクトリ単位でpackageを切るって話はしてない気がする

2023-11-02 07:04 UTC, hijiki51 commented on docs/chapter2/section1/0_setup.md
> +このまま演習を始めてしまうとファイルが長くなりすぎてしまうので、ファイルを別のパッケージとして分割します。
```
Packages
Goのプログラムは、パッケージ( package )で構成されます。

プログラムは main パッケージから開始されます。

このプログラムでは "fmt" と "math/rand" パッケージをインポート( import )しています。

規約で、パッケージ名はインポートパスの最後の要素と同じ名前になります。 例えば、インポートパスが "math/rand" のパッケージは、 package rand ステートメントで始まるファイル群で構成します。

Note: ここで実行するプログラムは常に同じ環境で実行されます ので、[擬似乱数](http://ja.wikipedia.org/wiki/%E6%93%AC%E4%BC%BC%E4%B9%B1%E6%95%B0)を返す [rand.Intn](https://golang.org/pkg/math/rand/#Rand.Intn) はいつも同じ数を返します。

(数を強制的に変える場合は、乱数生成でシードを与える必要があります。[rand.Seed](https://golang.org/pkg/math/rand/#Seed)を見てみてください。 playground 上での時間は一定なので他のものをシードとして使う必要があります。)
```

これしかないのでファイルパスとの対応がわからない

2023-11-02 07:08 UTC, pikachu0310 commented on docs/chapter2/section1/1_account.md
> +	Username string `json:"username,omitempty" form:"username"` // [!code ++]
使われていますね(無いと動かない)

2023-11-02 08:36 UTC, hijiki51 approved these changes

2023-11-19 12:58 UTC, merged